
================================================================
Welcome to SystemRescueCd 0.4.0 for SPARC    (www.system-rescue-cd.org)
================================================================

________BOOT IMAGES__________
* Type "rescuecd" to boot SystemRescueCd with the default options
* Type "config"   to see the silo.conf configuration file

________BOOT OPTIONS__________
* Add option "docache" to cache the system in RAM (it require 256MB
  of RAM, but allows you to unmount and eject the CD after booting)
* Add option "setkmap=x" to configure the keyboard with the x keymap 
  (x='fr' for french, 'de' for german, 'us', ...)
* Add option "dodhcp" to runs the DHCP client at boot time to get an IP

________BOOT PROBLEMS__________
* Type "boothelp" for help if you cannot boot this livecd on sparc

