export VIDEO_CARDS="vesa modesetting intel radeon nouveau nv dummy glint i128 i740 r128 mach64 rendition s3 s3virge siliconmotion trident sis savage cirrus voodoo sisusb ast tdfx via vmware apm"
export INPUT_DEVICES="keyboard vmmouse mouse evdev synaptics"
export FEATURES="parallel-fetch -collision-protect -protect-owned"
export MAKEOPTS="-j5"
export PORTAGE_NICENESS="19"
export ACCEPT_LICENSE="*"
export CFLAGS="-Os -mtune=i686 -pipe"
export CXXFLAGS="-Os -mtune=i686 -pipe"
export CONFIG_PROTECT="-*"
export PYTHON_TARGETS="python2_7"
