export VIDEO_CARDS="vesa nv ati dummy glint intel i128 i740 mach64 mga r128 rendition s3 s3virge siliconmotion trident sis savage cirrus voodoo openchrome sisusb ast tdfx"
export INPUT_DEVICES="keyboard vmmouse mouse evdev synaptics"
export FEATURES="parallel parallel-fetch -collision-protect -protect-owned"
export MAKEOPTS="-j5 --load-average=8"
export PORTAGE_NICENESS="19"
export ACCEPT_LICENSE="*"
export CFLAGS="-Os -mtune=i686 -pipe"
export CXXFLAGS="-Os -mtune=i686 -pipe"
