subarch: i486
version_stamp: baseos
target: stage3
rel_type: default
profile: default/linux/x86/13.0
snapshot: 20170725
source_subpath: default/stage2-i486-baseos
portage_confdir: /worksrc/sysresccd-src/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src/portage-overlay
