subarch: i686
target: stage2
version_stamp: baseos
rel_type: default
profile: default/linux/x86/13.0
snapshot: 20170901
source_subpath: default/stage1-i686-baseos
portage_confdir: /worksrc/sysresccd-src/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src/portage-overlay
