subarch: i386
version_stamp: 1.6-std
target: livecd-stage2
rel_type: default
profile: default/linux/x86/10.0
snapshot: 20100923
source_subpath: default/livecd-stage1-i386-1.6
portage_confdir: /worksrc/sysresccd-src-1.6/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src-1.6/portage-overlay

livecd/fstype: squashfs
livecd/cdtar: /usr/lib/catalyst/livecd/cdtar/isolinux-3.09-cdtar.tar.bz2
livecd/iso: /worksrc/isofiles/systemrescuecd-x86-current.iso
livecd/fsscript: /worksrc/sysresccd-src-1.6/mainfiles/fsscript.sh
livecd/splash_type:
livecd/splash_theme:
livecd/bootargs: dokeymap
livecd/gk_mainargs: --makeopts="-j5" --integrated-initramfs
livecd/type: generic-livecd
livecd/readme:
livecd/motd:
livecd/modblacklist:
livecd/root_overlay: /worksrc/sysresccd-src-1.6/overlay-squashfs-x86 /worksrc/sysresccd-bin-1.6/overlay-squashfs-x86
livecd/devmanager: udev
livecd/users:
livecd/volid: sysresccd

boot/kernel: rescuecd

boot/kernel/rescuecd/sources: sys-kernel/std-sources
boot/kernel/rescuecd/config: /worksrc/sysresccd-src-1.6/kernelcfg/config-x86-2.6.35-std160.conf
boot/kernel/rescuecd/use: pcmcia usb -X png truetype 
boot/kernel/rescuecd/extraversion: i386
boot/kernel/rescuecd/packages:
        sys-apps/sysresccd-scripts
        app-crypt/truecrypt
        net-dialup/speedtouch-usb
        net-dialup/rp-pppoe
        net-dialup/hcfpcimodem
        net-dialup/hsfmodem
        net-dialup/globespan-adsl
        net-misc/openswan
        sys-block/aic94xx-firmware
        net-wireless/acx-firmware
        net-wireless/atmel-firmware
        net-wireless/ipw2100-firmware
        net-wireless/ipw2200-firmware
        net-wireless/prism54-firmware
        net-wireless/zd1201-firmware
        net-wireless/zd1211-firmware
        net-wireless/madwifi-ng-tools
        net-wireless/bcm43xx-fwcutter
        net-wireless/b43-fwcutter
        net-wireless/ndiswrapper
        sys-fs/lufs
        sys-fs/lufis
        sys-fs/sshfs-fuse
        x11-wm/jwm
        sys-block/iscsitarget
        sys-apps/lm_sensors
        =sys-boot/grub-1.98
        sys-block/open-iscsi
        sys-fs/zfs-fuse
        sys-cluster/drbd
	x11-drivers/xf86-video-ati

livecd/unmerge:
	app-admin/eselect-opengl
	app-admin/perl-cleaner
	app-arch/rpm2targz
	sys-devel/bison
	sys-devel/bin86
	sys-devel/flex
	sys-kernel/std-sources
	sys-kernel/gentoo-sources
	dev-lang/nasm
	dev-libs/libxslt
	dev-util/yacc
	dev-util/gtk-doc
	dev-util/scons
	dev-util/ccache
	dev-util/ctags
	dev-util/intltool
	sys-apps/help2man
	sys-apps/miscfiles
	sys-apps/busybox
	sys-apps/texinfo
	sys-fs/progsreiserfs
	dev-python/pycrypto
	dev-python/python-fchksum
	dev-perl/Archive-Tar
	dev-perl/Compress-Raw-Zlib
	dev-perl/Compress-Zlib
	dev-perl/ExtUtils-CBuilder
	dev-perl/IO-Compress-Base
	dev-perl/IO-Compress-Zlib
	dev-perl/IO-String
	dev-perl/IO-Zlib
	dev-perl/XML-Parser
	dev-perl/extutils-parsexs
	dev-perl/module-build
	dev-perl/yaml
	perl-core/Scalar-List-Utils
	media-fonts/font-util
	x11-apps/xclock
	x11-apps/bdftopcf
	x11-terms/xterm
	x11-misc/imake
	x11-misc/util-macros
	x11-wm/twm
	sys-devel/gettext
	www-client/links
	app-admin/metalog
	x11-misc/makedepend
	x11-misc/xorg-cf-files
	x11-proto/bigreqsproto
	x11-proto/compositeproto
	x11-proto/damageproto
	x11-proto/dri2proto
	x11-proto/evieext
	x11-proto/fixesproto
	x11-proto/fontcacheproto
	x11-proto/fontsproto
	x11-proto/glproto
	x11-proto/inputproto
	x11-proto/printproto
	x11-proto/randrproto
	x11-proto/recordproto
	x11-proto/resourceproto
	x11-proto/scrnsaverproto
	x11-proto/trapproto
	x11-proto/videoproto
	x11-proto/xcmiscproto
	x11-proto/xextproto
	x11-proto/xf86bigfontproto
	x11-proto/xf86dgaproto
	x11-proto/xf86driproto
	x11-proto/xf86miscproto
	x11-proto/xf86rushproto
	x11-proto/xf86vidmodeproto
	x11-proto/xineramaproto
	sys-libs/libkudzu
	dev-lang/swig
	sys-kernel/genkernel
	media-libs/libafterimage
	x11-misc/gccmakedep
	sys-libs/cracklib
	sys-libs/db
	app-text/build-docbook-catalog
	app-text/sgml-common
	app-text/docbook-xsl-stylesheets
	app-text/docbook-xml-dtd
	app-text/gnome-doc-utils
	app-admin/eselect-xvmc
	dev-perl/Compress-Raw-Bzip2
	dev-perl/IO-Compress-Bzip2
	perl-core/Package-Constants
	dev-util/unifdef
	net-mail/mailbase
	mail-mta/ssmtp
	dev-util/xfce4-dev-tools
	dev-libs/xmlrpc-c
	dev-util/cmake
	dev-util/scons
	dev-libs/pkcs11-helper
	app-admin/sudo
	gnome-base/libgtop
	media-fonts/dejavu
	x11-libs/libgksu
	x11-libs/gksu
	dev-perl/XML-NamespaceSupport
	perl-core/Storable
	perl-core/Test-Simple
	dev-perl/XML-LibXML-Common
	dev-perl/XML-SAX
	virtual/perl-Test-Simple
	virtual/perl-Storable
	dev-perl/XML-LibXML
	dev-perl/XML-Simple
	games-misc/fortune-mod
	media-fonts/font-adobe-100dpi
	app-text/recode
	media-libs/glew
	media-sound/alsa-headers
	x11-drivers/xf86-video-fbdev
	app-admin/eselect-ruby
	dev-lang/ruby
	dev-util/gtk-doc-am
	app-text/scrollkeeper-dtd
	app-text/scrollkeeper
	app-text/rarian
	x11-drivers/xf86-video-vmware

livecd/empty:
	/var/cache/revdep-rebuild
	/etc/cron.daily
	/etc/cron.hourly
	/etc/cron.monthly
	/etc/cron.weekly
	/etc/logrotate.d
	/etc/modules.autoload.d
	/etc/runlevels/single
	/etc/skel
	/usr/lib/nfs
	/usr/local
	/usr/src
	/var/cache
	/var/empty
	/var/lock
	/var/log
	/var/run
	/var/spool
	/var/state
	/var/www
	/var/tmp
	/tmp

livecd/rm:
	/boot/System*
	/boot/initr*
	/boot/kernel*
	/root/.ccache
	/root/.viminfo
	/lib/dev-state
	/etc/*-
	/etc/*.old
	/etc/default/audioctl
	/etc/dispatch-conf.conf
	/etc/etc-update.conf
	/etc/hosts.bck
	/etc/issue*
	/etc/genkernel.conf
	/etc/make.conf.example
	/etc/splash
	/lib*/*.a
	/lib*/*.la
	/lib*/cpp
	/lib*/security/pam_chroot.so
	/lib*/security/pam_debug.so
	/lib*/security/pam_ftp.so
	/lib*/security/pam_issue.so
	/lib*/security/pam_mkhomedir.so
	/lib*/security/pam_postgresok.so
	/lib*/security/pam_rhosts_auth.so
	/lib*/security/pam_userdb.so
	/root/.bash_history
	/root/.svn
	/root/.zsh/.svn
	/usr/lib/mozilla-firefox/include
	/usr/lib/mozilla-firefox/idl
	/usr/include/mozilla-firefox
	/usr/include/unicode
	/usr/include/wx*
	/usr/lib/wx/include
	/usr/lib/gdkmm*
	/usr/lib/scons*
	/usr/share/doc/scons-*
	/usr/share/man/{man0p,man2,man3,man3p,man4,man6,man7,man9}
	/usr/share/man/{ca*,fr*,gl*,id*,hu*,it*,jp*,pl*,pt*,ru*,sk*,ug*,zh*}
	/usr/share/man/man1/{perl*,zshall.1.gz,ssl-*,openssl*}
	/usr/share/man/man5/{groff*,lj4*}
	/usr/sbin/archive-conf
	/usr/sbin/bootsplash*
	/usr/sbin/dispatch-conf
	/usr/sbin/fb*
	/usr/share/misc/*.old
	/usr/share/devhelp
	/usr/share/doc
	/usr/share/info
	/bin/*.old
	/sbin/*.old
	/usr/share/gtk-doc
	/usr/share/gtk-2.0
	/usr/bin/{addr2line,as,bashcomp-config,gfortran*,gmsgfmt,gprof}
	/usr/bin/{idle,ifnames,kernel-config,lex}
	/usr/bin/{pydoc,rc-config,rpm2tar,size,tclsh,wish}
	/usr/bin/{yacc,gtk-demo,cdda2wav,readcd,htmltopng}
	/usr/bin/{repoman,tbz2tool,xpak}
	/usr/lib/{libltdl.so,libtcl*,libtk*}
	/sbin/{kallsyms,kallsyms.static,ksyms,ksyms.static}
	/usr/lib/nss/*.a
	/usr/lib/nspr/*.a
	/usr/lib/{libbsd.a,libcurses.a,libpng.a}
	/usr/*/lib/{libbfd.a,libiberty.a,libopcodes.a}
	/usr/lib/binutils/*/*/libbfd.{a,la}
	/usr/lib/binutils/*/*/libopcodes.{a,la}
	/usr/include/GL
	/var/mail
	/make*
	/bin/.svn
	/var/.svn
	/var/lib/.svn
	/var/lib/clamav/.svn
	/usr/.svn
	/usr/sbin/.svn
	/etc/.svn
	/etc/X11/.svn
	/etc/X11/xinit/.svn
	/etc/udev/.svn
	/etc/udev/rules.d/.svn
	/usr/bin/{s2p,pod2text,perlcc,xsubpp,splain,h2xs,perlbug,psed,piconv,instmodsh,dprofpp,perldoc}
	/usr/bin/{pl2pm,perlivp,a2p,libnetcfg,find2perl,enc2xs,pstruct,pod2latex,cpan,c2ph}
	/usr/share/doc/{lrzsz*,minicom*,vte*,ckermit*}
	/usr/share/gtk-doc/html/vte*
	/usr/portage/{*-*,virtual,packages,scripts,metadata,licenses,eclass,distfiles,skel*,header.txt}
	/usr/portage/profiles/arch/{alpha,arm,hppa,ia64,m68k,mips,powerpc,ppc,ppc64,s390,sparc,x86-fbsd}
	/usr/portage/profiles/{default/bsd,default-bsd,hardened,obsolete,selinux,uclibc,ChangeLog}
	/usr/portage/profiles/default/linux/{alpha,arm,hppa,ia64,m68k,mips,powerpc,ppc,ppc64,s390,sparc,x86-fbsd}
	/usr/portage/profiles/default-linux/{alpha,arm,hppa,ia64,m68k,mips,powerpc,ppc,ppc64,s390,sparc,x86-fbsd}
	/usr/lib/perl5/5.8.8/Memoize/SDBM_File.pm
	/usr/lib/perl5/5.8.8/Memoize/AnyDBM_File.pm
	/usr/lib/perl5/5.8.8/Memoize/NDBM_File.pm
	/usr/lib/perl5/5.8.8/Memoize/Storable.pm
	/usr/lib/perl5/5.8.8/Memoize/ExpireTest.pm
	/usr/lib/perl5/5.8.8/Memoize/ExpireFile.pm
	/usr/lib/perl5/5.8.8/Memoize/Expire.pm
	/usr/lib/perl5/5.8.8/Tie/Hash.pm
	/usr/lib/perl5/5.8.8/Tie/SubstrHash.pm
	/usr/lib/perl5/5.8.8/Tie/Array.pm
	/usr/lib/perl5/5.8.8/Tie/Memoize.pm
	/usr/lib/perl5/5.8.8/Tie/RefHash.pm
	/usr/lib/perl5/5.8.8/Tie/Handle.pm
	/usr/lib/perl5/5.8.8/Tie/File.pm
	/usr/lib/perl5/5.8.8/Tie/Scalar.pm
	/usr/lib/perl5/5.8.8/Math/BigFloat/Trace.pm
	/usr/lib/perl5/5.8.8/Math/BigInt.pm
	/usr/lib/perl5/5.8.8/Math/Complex.pm
	/usr/lib/perl5/5.8.8/Math/BigRat.pm
	/usr/lib/perl5/5.8.8/Math/Trig.pm
	/usr/lib/perl5/5.8.8/Math/BigInt/Calc.pm
	/usr/lib/perl5/5.8.8/Math/BigInt/CalcEmu.pm
	/usr/lib/perl5/5.8.8/Math/BigInt/Trace.pm
	/usr/lib/perl5/5.8.8/Math/BigFloat.pm
	/usr/lib/perl5/5.8.8/assert.pl
	/usr/lib/perl5/5.8.8/Filter/Simple.pm
	/usr/lib/perl5/5.8.8/importenv.pl
	/usr/lib/perl5/5.8.8/Thread/Queue.pm
	/usr/lib/perl5/5.8.8/Thread/Semaphore.pm
	/usr/lib/perl5/5.8.8/Env.pm
	/usr/lib/perl5/5.8.8/perl5db.pl
	/usr/lib/perl5/5.8.8/dumpvar.pl
	/usr/lib/perl5/5.8.8/Unicode/UCD.pm
	/usr/lib/perl5/5.8.8/Unicode/Collate.pm
	/usr/lib/perl5/5.8.8/Unicode/Collate/keys.txt
	/usr/lib/perl5/5.8.8/Digest.pm
	/usr/lib/perl5/5.8.8/Shell.pm
	/usr/lib/perl5/5.8.8/DBM_Filter.pm
	/usr/lib/perl5/5.8.8/PerlIO/via/QuotedPrint.pm
	/usr/lib/perl5/5.8.8/i486-linux/Filter/Util/Call.pm
	/usr/lib/perl5/5.8.8/i486-linux/.packlist
	/usr/lib/perl5/5.8.8/i486-linux/Unicode/Normalize.pm
	/usr/lib/perl5/5.8.8/i486-linux/PerlIO/encoding.pm
	/usr/lib/perl5/5.8.8/i486-linux/PerlIO/via.pm
	/usr/lib/perl5/5.8.8/i486-linux/PerlIO/scalar.pm
	/usr/lib/perl5/5.8.8/i486-linux/SDBM_File.pm
	/usr/lib/perl5/5.8.8/i486-linux/O.pm
	/usr/lib/perl5/5.8.8/i486-linux/MIME/QuotedPrint.pm
	/usr/lib/perl5/5.8.8/i486-linux/MIME/Base64.pm
	/usr/lib/perl5/5.8.8/i486-linux/I18N/Langinfo.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode.pm
	/usr/lib/perl5/5.8.8/i486-linux/Opcode.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/KR.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Byte.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Symbol.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/CN.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/JP.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/CJKConstants.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/TW.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/EBCDIC.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Unicode.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Encoding.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Encoder.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Alias.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Guess.pm
	/usr/lib/perl5/5.8.8/i486-linux/Encode/Config.pm
	/usr/lib/perl5/5.8.8/i486-linux/threads/shared.pm
	/usr/lib/perl5/5.8.8/i486-linux/IPC/Msg.pm
	/usr/lib/perl5/5.8.8/i486-linux/IPC/SysV.pm
	/usr/lib/perl5/5.8.8/i486-linux/IPC/Semaphore.pm
	/usr/lib/perl5/5.8.8/i486-linux/ByteLoader.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Bblock.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/C.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Showlex.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Terse.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Bytecode.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Disassembler.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Stackobj.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Xref.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/CC.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Asmdata.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Debug.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Concise.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Lint.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Assembler.pm
	/usr/lib/perl5/5.8.8/i486-linux/B/Stash.pm
	/usr/lib/perl5/5.8.8/i486-linux/IO/Poll.pm
	/usr/lib/perl5/5.8.8/i486-linux/IO/Dir.pm
	/usr/lib/perl5/5.8.8/i486-linux/Safe.pm
	/usr/lib/perl5/5.8.8/i486-linux/POSIX.pod
	/usr/lib/perl5/5.8.8/i486-linux/Devel/PPPort.pm
	/usr/lib/perl5/5.8.8/i486-linux/Devel/Peek.pm
	/usr/lib/perl5/5.8.8/i486-linux/Devel/DProf.pm
	/usr/lib/perl5/5.8.8/i486-linux/XS/APItest.pm
	/usr/lib/perl5/5.8.8/i486-linux/XS/Typemap.pm
	/usr/lib/perl5/5.8.8/i486-linux/Digest/MD5.pm
	/usr/lib/perl5/5.8.8/i486-linux/Config.pod
	/usr/lib/perl5/5.8.8/i486-linux/auto/Filter/Util/Call/Call.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Filter/Util/Call/Call.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/ByteLoader/ByteLoader.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/ByteLoader/ByteLoader.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Unicode/Normalize/Normalize.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Unicode/Normalize/Normalize.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/PerlIO/scalar/scalar.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/PerlIO/scalar/scalar.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/PerlIO/via/via.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/PerlIO/via/via.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/PerlIO/encoding/encoding.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/PerlIO/encoding/encoding.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/File/Glob/Glob.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/sdbm/extralibs.ld
	/usr/lib/perl5/5.8.8/i486-linux/auto/attrs/attrs.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/attrs/attrs.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Opcode/Opcode.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Opcode/Opcode.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/MIME/Base64/Base64.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/MIME/Base64/Base64.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/I18N/Langinfo/Langinfo.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/I18N/Langinfo/Langinfo.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/I18N/Langinfo/autosplit.ix
	/usr/lib/perl5/5.8.8/i486-linux/auto/SDBM_File/SDBM_File.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/SDBM_File/SDBM_File.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/EBCDIC/EBCDIC.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/EBCDIC/EBCDIC.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Unicode/Unicode.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Unicode/Unicode.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/CN/CN.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/CN/CN.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Byte/Byte.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Byte/Byte.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/KR/KR.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/KR/KR.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/TW/TW.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/TW/TW.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Symbol/Symbol.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Symbol/Symbol.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Encode.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/Encode.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/JP/JP.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Encode/JP/JP.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/threads/shared/shared.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/threads/shared/shared.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/threads/threads.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/threads/threads.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Data/Dumper/Dumper.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/IPC/SysV/SysV.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/IPC/SysV/SysV.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Socket/Socket.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/DynaLoader/extralibs.ld
	/usr/lib/perl5/5.8.8/i486-linux/auto/DynaLoader/DynaLoader.a
	/usr/lib/perl5/5.8.8/i486-linux/auto/DynaLoader/dl_find_symbol_anywhere.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/DynaLoader/autosplit.ix
	/usr/lib/perl5/5.8.8/i486-linux/auto/DynaLoader/dl_expandspec.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/B/B.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/B/B.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/B/C/C.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/B/C/C.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/List/Util/Util.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/List/Util/Util.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Fcntl/Fcntl.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/IO/IO.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/scanf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/closedir.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/memcmp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getgrnam.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fputs.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strncpy.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/unimpl.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getuid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/putc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getgid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/atol.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strncmp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/rand.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fscanf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/isatty.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/setjmp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/assert.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/setbuf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/longjmp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/labs.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strtok.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getpgrp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/memset.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/sigsetjmp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strcmp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/chown.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fread.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/execlp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getgroups.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fabs.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/chdir.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/rename.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getpwuid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/atoi.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fileno.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fseek.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fclose.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/qsort.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/execv.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/realloc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getenv.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/ungetc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strlen.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/div.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/vprintf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strstr.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/execvp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/umask.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/usage.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/unlink.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/pow.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/kill.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/memchr.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/rmdir.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/gets.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/ftell.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/redef.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/malloc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fwrite.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getpid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strchr.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strrchr.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/log.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/perror.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/vfprintf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fgetpos.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fflush.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/localtime.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/opendir.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strcspn.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getppid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strspn.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/alarm.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/sscanf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/utime.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fcntl.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/calloc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/rewinddir.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fopen.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/atof.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fsetpos.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/srand.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/exp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fdopen.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/feof.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/clearerr.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getlogin.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/atan2.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/freopen.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/mkdir.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/tolower.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/putchar.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/bsearch.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/offsetof.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/gmtime.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/raise.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/free.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strerror.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/wait.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/execve.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/toupper.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getchar.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/time.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strpbrk.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fputc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/vsprintf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strncat.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/abs.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strcpy.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getegid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fsync.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/printf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/strcat.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/siglongjmp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/setvbuf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/waitpid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/ferror.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/link.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/sqrt.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/readdir.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/sleep.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/sprintf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/memcpy.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/ldiv.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/puts.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fprintf.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/exit.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fork.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/creat.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/sin.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/atexit.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/execl.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fgetc.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/errno.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/execle.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getgrgid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/fgets.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/system.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/chmod.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/memmove.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/rewind.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/geteuid.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/getpwnam.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/cos.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/POSIX/remove.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/re/re.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/logcarp.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/logcroak.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/store_fd.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/_freeze.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/read_magic.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/fd_retrieve.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/freeze.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/lock_store.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/_store_fd.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/CAN_FLOCK.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/show_file_magic.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/lock_nstore.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/nstore.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/lock_retrieve.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/Storable.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/nstore_fd.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/nfreeze.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Storable/thaw.al
	/usr/lib/perl5/5.8.8/i486-linux/auto/Devel/DProf/DProf.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Devel/DProf/DProf.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Devel/Peek/Peek.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Devel/Peek/Peek.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Devel/PPPort/PPPort.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Devel/PPPort/PPPort.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/XS/Typemap/Typemap.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/XS/Typemap/Typemap.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/XS/APItest/APItest.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/XS/APItest/APItest.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Digest/MD5/MD5.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Digest/MD5/MD5.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Cwd/Cwd.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Time/HiRes/HiRes.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Time/HiRes/HiRes.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Sys/Hostname/Hostname.bs
	/usr/lib/perl5/5.8.8/i486-linux/auto/Sys/Hostname/Hostname.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Sys/Hostname/autosplit.ix
	/usr/lib/perl5/5.8.8/i486-linux/auto/Sys/Syslog/Syslog.so
	/usr/lib/perl5/5.8.8/i486-linux/auto/Sys/Syslog/Syslog.bs
	/usr/lib/perl5/5.8.8/i486-linux/Time/HiRes.pm
	/usr/lib/perl5/5.8.8/i486-linux/Sys/Syslog.pm
	/usr/lib/perl5/5.8.8/i486-linux/Sys/Hostname.pm
	/usr/lib/perl5/5.8.8/User/grent.pm
	/usr/lib/perl5/5.8.8/User/pwent.pm
	/usr/lib/perl5/5.8.8/Test.pm
	/usr/lib/perl5/5.8.8/getcwd.pl
	/usr/lib/perl5/5.8.8/fastcwd.pl
	/usr/lib/perl5/5.8.8/Class/ISA.pm
	/usr/lib/perl5/5.8.8/finddepth.pl
	/usr/lib/perl5/5.8.8/Term/ANSIColor.pm
	/usr/lib/perl5/5.8.8/Term/ReadLine.pm
	/usr/lib/perl5/5.8.8/Term/Complete.pm
	/usr/lib/perl5/5.8.8/Term/Cap.pm
	/usr/lib/perl5/5.8.8/unicore/NormalizationCorrections.txt
	/usr/lib/perl5/5.8.8/unicore/Jamo.txt
	/usr/lib/perl5/5.8.8/unicore/To/Title.pl
	/usr/lib/perl5/5.8.8/unicore/To/Digit.pl
	/usr/lib/perl5/5.8.8/unicore/EastAsianWidth.txt
	/usr/lib/perl5/5.8.8/unicore/Name.pl
	/usr/lib/perl5/5.8.8/unicore/version
	/usr/lib/perl5/5.8.8/unicore/lib/hst/LVT.pl
	/usr/lib/perl5/5.8.8/unicore/lib/hst/V.pl
	/usr/lib/perl5/5.8.8/unicore/lib/hst/L.pl
	/usr/lib/perl5/5.8.8/unicore/lib/hst/LV.pl
	/usr/lib/perl5/5.8.8/unicore/lib/hst/T.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ea/Na.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ea/F.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ea/N.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ea/W.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ea/A.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ea/H.pl
	/usr/lib/perl5/5.8.8/unicore/lib/nt/De.pl
	/usr/lib/perl5/5.8.8/unicore/lib/nt/Di.pl
	/usr/lib/perl5/5.8.8/unicore/lib/nt/Nu.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/GL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/NU.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/SG.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/AI.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/QU.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/OP.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/NS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/H2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/NL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/BA.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/JT.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/SY.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/ID.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/EX.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/BK.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/H3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/WJ.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/BB.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/IN.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/CL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/CM.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/AL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/HY.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/PO.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/IS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/SP.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/CB.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/LF.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/SA.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/JV.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/JL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/ZW.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/XX.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/CR.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/PR.pl
	/usr/lib/perl5/5.8.8/unicore/lib/lb/B2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/jt/D.pl
	/usr/lib/perl5/5.8.8/unicore/lib/jt/C.pl
	/usr/lib/perl5/5.8.8/unicore/lib/jt/R.pl
	/usr/lib/perl5/5.8.8/unicore/lib/jt/U.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/WS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/S.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/RLO.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/NSM.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/ES.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/PDF.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/ET.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/LRO.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/L.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/R.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/LRE.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/BN.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/ON.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/RLE.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/B.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/CS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/AN.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/EN.pl
	/usr/lib/perl5/5.8.8/unicore/lib/bc/AL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/can.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/fra.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/init.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/iso.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/sqr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/vert.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/fin.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/nar.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/wide.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/sml.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/font.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/med.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/com.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/enc.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/sup.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/nb.pl
	/usr/lib/perl5/5.8.8/unicore/lib/dt/sub.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/NR.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/DB.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/BL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/OV.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/ATBL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/AR.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/ATB.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/BR.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/ATAR.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/L.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/R.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/VR.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/B.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/AL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/A.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/IS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/NK.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/KV.pl
	/usr/lib/perl5/5.8.8/unicore/lib/ccc/DA.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Goth.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Khar.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InEnclo2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Co.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherDef.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLinear.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/XDigit.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHalfwi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLinea2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Runr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/HexDigit.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/S.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Nonchara.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InAegean.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/BidiCont.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Any.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkStr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InYijing.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Dash2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMisce5.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InOsmany.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Zs.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGlagol.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Mc.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTaiXua.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cprt.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ugar.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InNewTai.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSuppl3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Buhd.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKangxi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InOriya.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cf.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBopom2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Nl.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hyphen.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Alphabet.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/SoftDott.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InArabi2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Title.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHebrew.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cn.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSuppl2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Term.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/UnifiedI.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Lo.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/PatWS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/SylotiNa.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InDevana.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Telu.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLatin1.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Knda.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKhmerS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/GrLink.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OldPersi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCombi3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSpacin.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/M.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/N.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMathem.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InModifi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMongol.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/C.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkSym.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/PatternW.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTagban.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Sm.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Sc.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Brai.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InShavia.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/AsciiHex.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Dep.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCombi2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Syrc.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InVertic.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGeorg2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCyprio.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/IDST.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Sterm2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InAlphab.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OIDS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHangul.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Extender.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTamil.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/LogicalO.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Math.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InByzant.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCombin.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkUn2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Limb.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/LC.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHiraga.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMalaya.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/VS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGurmuk.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBraill.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OMath.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/So.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InArrows.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSyriac.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Grek.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkUn3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Blank.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKanbun.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Diacriti.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hira.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBengal.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Sinh.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cs.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Radical2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ethi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTaiLe.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Osma.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCoptic.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/NChar.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Alnum.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InUgarit.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ideograp.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Dsrt.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OUpper.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Mn.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGenera.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Mlym.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKannad.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InContro.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InEnclos.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGujara.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Thaa.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherIdS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTibeta.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InDesere.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBuhid.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cher.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/L.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InIpaExt.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKatak2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGreekA.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Quotatio.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKataka.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Punct.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cyrl.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InUnifie.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hano.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherUpp.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Lowercas.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLowSur.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Taml.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InThai.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSmallF.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCyrill.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InArabi3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/AHex.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hex.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ideo.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Z.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLatin2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSuppl5.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Orya.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKharos.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHighSu.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Tagb.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InYiRadi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLetter.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLao.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Beng.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCyril2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OldItali.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/ASCII.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/P.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGeomet.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkCo4.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cntrl.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/_CanonDC.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBugine.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Pc.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Mymr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hang.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InKhmer.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/WhiteSpa.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OAlpha.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Pe.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSuppl6.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Deprecat.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCurren.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCherok.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBopomo.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Gujr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Pf.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/IdsTrina.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Pi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Grapheme.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InPrivat.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/_CombAbo.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGeorgi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InOldIta.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Zp.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Cc.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Copt.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Assigned.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ext.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Lt.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ps.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Tglg.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkCom.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Qaai.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InArmeni.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSinhal.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSpecia.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/IdStart.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Glag.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSyloti.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGothic.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSupers.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InEthio2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSupple.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Armn.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/TaiLe.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InNumber.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/IDSB.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Dash.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Space.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/STerm.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherIdC.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBasicL.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Latn.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMisce2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InVariat.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/_CaseIgn.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTifina.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/WSpace.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/QMark.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkUni.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InEthiop.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InYiSyll.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InArabi4.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OIDC.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/LOE.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkRad.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHanuno.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkCo3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherGra.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InVaria2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Lower.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Deva.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTags.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Terminal.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hyphen2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/JoinCont.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMyanma.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMathe2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Lu.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherAlp.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Sk.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InPhone2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Geor.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherLow.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/No.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/JoinC.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Alpha.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InEthio3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Yiii.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Mong.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/NewTaiLu.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Thai.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InRunic.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCombi4.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMusica.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InCjkCo2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Pd.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMisce3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Uppercas.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Po.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTagalo.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Radical.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Bugi.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InIdeogr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Shaw.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Dia.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHangu2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InArabic.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OGrExt.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMisce4.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Kana.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InTelugu.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Lm.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InThaana.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Khmr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Me.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InGreekE.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InOldPer.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InSuppl4.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/LinearB.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/PatternS.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Variatio.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Bopo.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hebr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InAncie2.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Canadian.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLatinE.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/SpacePer.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Tfng.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InOgham.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Graph.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Zyyy.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHangu3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Guru.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OtherMat.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Upper.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLimbu.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InDingba.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Tibt.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Print.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InMiscel.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InHighPr.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/UIdeo.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/ODI.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ogam.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Ll.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/IdContin.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InPhonet.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/BidiC.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Arab.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/IdsBinar.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Hani.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InLatin3.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/PatSyn.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Zl.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBlockE.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Nd.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InOptica.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/SD.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InBoxDra.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/InAncien.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/OLower.pl
	/usr/lib/perl5/5.8.8/unicore/lib/gc_sc/Laoo.pl
	/usr/lib/perl5/5.8.8/unicore/ReadMe.txt
	/usr/lib/perl5/5.8.8/unicore/Blocks.txt
	/usr/lib/perl5/5.8.8/unicore/Index.txt
	/usr/lib/perl5/5.8.8/unicore/LineBreak.txt
	/usr/lib/perl5/5.8.8/unicore/CompositionExclusions.txt
	/usr/lib/perl5/5.8.8/unicore/HangulSyllableType.txt
	/usr/lib/perl5/5.8.8/unicore/Properties
	/usr/lib/perl5/5.8.8/unicore/NamesList.txt
	/usr/lib/perl5/5.8.8/unicore/PropList.txt
	/usr/lib/perl5/5.8.8/unicore/ArabicShaping.txt
	/usr/lib/perl5/5.8.8/unicore/PropValueAliases.txt
	/usr/lib/perl5/5.8.8/unicore/SpecialCasing.txt
	/usr/lib/perl5/5.8.8/unicore/CombiningClass.pl
	/usr/lib/perl5/5.8.8/unicore/mktables.lst
	/usr/lib/perl5/5.8.8/unicore/StandardizedVariants.txt
	/usr/lib/perl5/5.8.8/unicore/NamedSequences.txt
	/usr/lib/perl5/5.8.8/unicore/UnicodeData.txt
	/usr/lib/perl5/5.8.8/unicore/Decomposition.pl
	/usr/lib/perl5/5.8.8/unicore/PropertyAliases.txt
	/usr/lib/perl5/5.8.8/unicore/BidiMirroring.txt
	/usr/lib/perl5/5.8.8/unicore/Scripts.txt
	/usr/lib/perl5/5.8.8/unicore/CaseFolding.txt
	/usr/lib/perl5/5.8.8/unicore/mktables
	/usr/lib/perl5/5.8.8/cacheout.pl
	/usr/lib/perl5/5.8.8/AnyDBM_File.pm
	/usr/lib/perl5/5.8.8/I18N/LangTags/Detect.pm
	/usr/lib/perl5/5.8.8/I18N/LangTags/List.pm
	/usr/lib/perl5/5.8.8/I18N/Collate.pm
	/usr/lib/perl5/5.8.8/I18N/LangTags.pm
	/usr/lib/perl5/5.8.8/Memoize.pm
	/usr/lib/perl5/5.8.8/dotsh.pl
	/usr/lib/perl5/5.8.8/timelocal.pl
	/usr/lib/perl5/5.8.8/CGI.pm
	/usr/lib/perl5/5.8.8/shellwords.pl
	/usr/lib/perl5/5.8.8/bigint.pl
	/usr/lib/perl5/5.8.8/validate.pl
	/usr/lib/perl5/5.8.8/Encode/PerlIO.pod
	/usr/lib/perl5/5.8.8/Encode/ConfigLocal_PM.e2x
	/usr/lib/perl5/5.8.8/Encode/Unicode/UTF7.pm
	/usr/lib/perl5/5.8.8/Encode/_PM.e2x
	/usr/lib/perl5/5.8.8/Encode/Makefile_PL.e2x
	/usr/lib/perl5/5.8.8/Encode/MIME/Header.pm
	/usr/lib/perl5/5.8.8/Encode/MIME/Header/ISO_2022_JP.pm
	/usr/lib/perl5/5.8.8/Encode/Supported.pod
	/usr/lib/perl5/5.8.8/Encode/Changes.e2x
	/usr/lib/perl5/5.8.8/Encode/CN/HZ.pm
	/usr/lib/perl5/5.8.8/Encode/encode.h
	/usr/lib/perl5/5.8.8/Encode/_T.e2x
	/usr/lib/perl5/5.8.8/Encode/README.e2x
	/usr/lib/perl5/5.8.8/Encode/KR/2022_KR.pm
	/usr/lib/perl5/5.8.8/Encode/JP/H2Z.pm
	/usr/lib/perl5/5.8.8/Encode/JP/JIS7.pm
	/usr/lib/perl5/5.8.8/Hash/Util.pm
	/usr/lib/perl5/5.8.8/CGI/Carp.pm
	/usr/lib/perl5/5.8.8/CGI/Pretty.pm
	/usr/lib/perl5/5.8.8/CGI/Apache.pm
	/usr/lib/perl5/5.8.8/CGI/Cookie.pm
	/usr/lib/perl5/5.8.8/CGI/Push.pm
	/usr/lib/perl5/5.8.8/CGI/eg/crash.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/caution.xbm
	/usr/lib/perl5/5.8.8/CGI/eg/dna_small_gif.uu
	/usr/lib/perl5/5.8.8/CGI/eg/customize.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/internal_links.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/tryit.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/multiple_forms.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/nph-multipart.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/clickable_image.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/popup.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/nph-clock.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/RunMeFirst
	/usr/lib/perl5/5.8.8/CGI/eg/file_upload.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/index.html
	/usr/lib/perl5/5.8.8/CGI/eg/diff_upload.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/save_state.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/monty.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/cookie.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/make_links.pl
	/usr/lib/perl5/5.8.8/CGI/eg/wilogo_gif.uu
	/usr/lib/perl5/5.8.8/CGI/eg/frameset.cgi
	/usr/lib/perl5/5.8.8/CGI/eg/javascript.cgi
	/usr/lib/perl5/5.8.8/CGI/Fast.pm
	/usr/lib/perl5/5.8.8/CGI/Switch.pm
	/usr/lib/perl5/5.8.8/CGI/Util.pm
	/usr/lib/perl5/5.8.8/open2.pl
	/usr/lib/perl5/5.8.8/UNIVERSAL.pm
	/usr/lib/perl5/5.8.8/Benchmark.pm
	/usr/lib/perl5/5.8.8/DB.pm
	/usr/lib/perl5/5.8.8/open3.pl
	/usr/lib/perl5/5.8.8/SelfLoader.pm
	/usr/lib/perl5/5.8.8/NEXT.pm
	/usr/lib/perl5/5.8.8/tainted.pl
	/usr/lib/perl5/5.8.8/B/disassemble
	/usr/lib/perl5/5.8.8/B/assemble
	/usr/lib/perl5/5.8.8/B/makeliblinks
	/usr/lib/perl5/5.8.8/B/cc_harness
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToText.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/GetOptsOO.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToXml.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToChecker.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/BaseTo.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToTk.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToRtf.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToPod.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToNroff.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc/ToMan.pm
	/usr/lib/perl5/5.8.8/Pod/Find.pm
	/usr/lib/perl5/5.8.8/Pod/Html.pm
	/usr/lib/perl5/5.8.8/Pod/LaTeX.pm
	/usr/lib/perl5/5.8.8/Pod/Checker.pm
	/usr/lib/perl5/5.8.8/Pod/Perldoc.pm
	/usr/lib/perl5/5.8.8/Pod/Plainer.pm
	/usr/lib/perl5/5.8.8/Pod/Functions.pm
	/usr/lib/perl5/5.8.8/Pod/ParseUtils.pm
	/usr/lib/perl5/5.8.8/Pod/Text/Color.pm
	/usr/lib/perl5/5.8.8/Pod/Text/Overstrike.pm
	/usr/lib/perl5/5.8.8/Pod/Text/Termcap.pm
	/usr/lib/perl5/5.8.8/Pod/PlainText.pm
	/usr/lib/perl5/5.8.8/pwd.pl
	/usr/lib/perl5/5.8.8/look.pl
	/usr/lib/perl5/5.8.8/flush.pl
	/usr/lib/perl5/5.8.8/exceptions.pl
	/usr/lib/perl5/5.8.8/pod/perlmod.pod
	/usr/lib/perl5/5.8.8/pod/perlepoc.pod
	/usr/lib/perl5/5.8.8/pod/perlmodstyle.pod
	/usr/lib/perl5/5.8.8/pod/perlnetware.pod
	/usr/lib/perl5/5.8.8/pod/perl570delta.pod
	/usr/lib/perl5/5.8.8/pod/perlcheat.pod
	/usr/lib/perl5/5.8.8/pod/perlport.pod
	/usr/lib/perl5/5.8.8/pod/perl561delta.pod
	/usr/lib/perl5/5.8.8/pod/perliol.pod
	/usr/lib/perl5/5.8.8/pod/perlhpux.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq3.pod
	/usr/lib/perl5/5.8.8/pod/perlmodinstall.pod
	/usr/lib/perl5/5.8.8/pod/perlmachten.pod
	/usr/lib/perl5/5.8.8/pod/perl58delta.pod
	/usr/lib/perl5/5.8.8/pod/perltie.pod
	/usr/lib/perl5/5.8.8/pod/perlbeos.pod
	/usr/lib/perl5/5.8.8/pod/perlxstut.pod
	/usr/lib/perl5/5.8.8/pod/perl585delta.pod
	/usr/lib/perl5/5.8.8/pod/perlguts.pod
	/usr/lib/perl5/5.8.8/pod/perltrap.pod
	/usr/lib/perl5/5.8.8/pod/perlmacosx.pod
	/usr/lib/perl5/5.8.8/pod/perlopentut.pod
	/usr/lib/perl5/5.8.8/pod/perlmodlib.pod
	/usr/lib/perl5/5.8.8/pod/perlintro.pod
	/usr/lib/perl5/5.8.8/pod/perldebtut.pod
	/usr/lib/perl5/5.8.8/pod/perlcygwin.pod
	/usr/lib/perl5/5.8.8/pod/perlapio.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq9.pod
	/usr/lib/perl5/5.8.8/pod/perltru64.pod
	/usr/lib/perl5/5.8.8/pod/perlvar.pod
	/usr/lib/perl5/5.8.8/pod/perlfork.pod
	/usr/lib/perl5/5.8.8/pod/perl572delta.pod
	/usr/lib/perl5/5.8.8/pod/perllol.pod
	/usr/lib/perl5/5.8.8/pod/perl5005delta.pod
	/usr/lib/perl5/5.8.8/pod/perlsub.pod
	/usr/lib/perl5/5.8.8/pod/perlos400.pod
	/usr/lib/perl5/5.8.8/pod/perlunicode.pod
	/usr/lib/perl5/5.8.8/pod/perluniintro.pod
	/usr/lib/perl5/5.8.8/pod/perlreftut.pod
	/usr/lib/perl5/5.8.8/pod/perlutil.pod
	/usr/lib/perl5/5.8.8/pod/perlhurd.pod
	/usr/lib/perl5/5.8.8/pod/perlmint.pod
	/usr/lib/perl5/5.8.8/pod/perl588delta.pod
	/usr/lib/perl5/5.8.8/pod/perldebguts.pod
	/usr/lib/perl5/5.8.8/pod/perl5004delta.pod
	/usr/lib/perl5/5.8.8/pod/perldgux.pod
	/usr/lib/perl5/5.8.8/pod/perlglossary.pod
	/usr/lib/perl5/5.8.8/pod/perl584delta.pod
	/usr/lib/perl5/5.8.8/pod/perl581delta.pod
	/usr/lib/perl5/5.8.8/pod/perlpodspec.pod
	/usr/lib/perl5/5.8.8/pod/perlre.pod
	/usr/lib/perl5/5.8.8/pod/perlboot.pod
	/usr/lib/perl5/5.8.8/pod/perlrequick.pod
	/usr/lib/perl5/5.8.8/pod/perlbot.pod
	/usr/lib/perl5/5.8.8/pod/perlcompile.pod
	/usr/lib/perl5/5.8.8/pod/perljp.pod
	/usr/lib/perl5/5.8.8/pod/perlobj.pod
	/usr/lib/perl5/5.8.8/pod/perllinux.pod
	/usr/lib/perl5/5.8.8/pod/perl587delta.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq5.pod
	/usr/lib/perl5/5.8.8/pod/perlembed.pod
	/usr/lib/perl5/5.8.8/pod/perlplan9.pod
	/usr/lib/perl5/5.8.8/pod/perlreref.pod
	/usr/lib/perl5/5.8.8/pod/perlsolaris.pod
	/usr/lib/perl5/5.8.8/pod/perlwin32.pod
	/usr/lib/perl5/5.8.8/pod/perllexwarn.pod
	/usr/lib/perl5/5.8.8/pod/perldata.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq7.pod
	/usr/lib/perl5/5.8.8/pod/perlsec.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq8.pod
	/usr/lib/perl5/5.8.8/pod/perlqnx.pod
	/usr/lib/perl5/5.8.8/pod/perlfreebsd.pod
	/usr/lib/perl5/5.8.8/pod/perl.pod
	/usr/lib/perl5/5.8.8/pod/perlop.pod
	/usr/lib/perl5/5.8.8/pod/perlnumber.pod
	/usr/lib/perl5/5.8.8/pod/perlos2.pod
	/usr/lib/perl5/5.8.8/pod/perl582delta.pod
	/usr/lib/perl5/5.8.8/pod/perlstyle.pod
	/usr/lib/perl5/5.8.8/pod/perlvmesa.pod
	/usr/lib/perl5/5.8.8/pod/perlsyn.pod
	/usr/lib/perl5/5.8.8/pod/perldsc.pod
	/usr/lib/perl5/5.8.8/pod/perlpacktut.pod
	/usr/lib/perl5/5.8.8/pod/perl573delta.pod
	/usr/lib/perl5/5.8.8/pod/perlos390.pod
	/usr/lib/perl5/5.8.8/pod/perlform.pod
	/usr/lib/perl5/5.8.8/pod/perl586delta.pod
	/usr/lib/perl5/5.8.8/pod/perldebug.pod
	/usr/lib/perl5/5.8.8/pod/perltoot.pod
	/usr/lib/perl5/5.8.8/pod/perlopenbsd.pod
	/usr/lib/perl5/5.8.8/pod/perltodo.pod
	/usr/lib/perl5/5.8.8/pod/perl56delta.pod
	/usr/lib/perl5/5.8.8/pod/perlirix.pod
	/usr/lib/perl5/5.8.8/pod/perlce.pod
	/usr/lib/perl5/5.8.8/pod/perlipc.pod
	/usr/lib/perl5/5.8.8/pod/perldbmfilter.pod
	/usr/lib/perl5/5.8.8/pod/perlothrtut.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq1.pod
	/usr/lib/perl5/5.8.8/pod/perlclib.pod
	/usr/lib/perl5/5.8.8/pod/perlhist.pod
	/usr/lib/perl5/5.8.8/pod/perldelta.pod
	/usr/lib/perl5/5.8.8/pod/perllocale.pod
	/usr/lib/perl5/5.8.8/pod/perlretut.pod
	/usr/lib/perl5/5.8.8/pod/perlcall.pod
	/usr/lib/perl5/5.8.8/pod/perldos.pod
	/usr/lib/perl5/5.8.8/pod/perlfunc.pod
	/usr/lib/perl5/5.8.8/pod/perlxs.pod
	/usr/lib/perl5/5.8.8/pod/perlref.pod
	/usr/lib/perl5/5.8.8/pod/perlbs2000.pod
	/usr/lib/perl5/5.8.8/pod/perlrun.pod
	/usr/lib/perl5/5.8.8/pod/perltw.pod
	/usr/lib/perl5/5.8.8/pod/perlvms.pod
	/usr/lib/perl5/5.8.8/pod/perlcn.pod
	/usr/lib/perl5/5.8.8/pod/perlpod.pod
	/usr/lib/perl5/5.8.8/pod/perlbook.pod
	/usr/lib/perl5/5.8.8/pod/perl571delta.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq.pod
	/usr/lib/perl5/5.8.8/pod/perlnewmod.pod
	/usr/lib/perl5/5.8.8/pod/a2p.pod
	/usr/lib/perl5/5.8.8/pod/perlmacos.pod
	/usr/lib/perl5/5.8.8/pod/perlamiga.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq6.pod
	/usr/lib/perl5/5.8.8/pod/perlgpl.pod
	/usr/lib/perl5/5.8.8/pod/perlhack.pod
	/usr/lib/perl5/5.8.8/pod/perl583delta.pod
	/usr/lib/perl5/5.8.8/pod/perlmpeix.pod
	/usr/lib/perl5/5.8.8/pod/perlartistic.pod
	/usr/lib/perl5/5.8.8/pod/perlapi.pod
	/usr/lib/perl5/5.8.8/pod/perlaix.pod
	/usr/lib/perl5/5.8.8/pod/perltooc.pod
	/usr/lib/perl5/5.8.8/pod/perltoc.pod
	/usr/lib/perl5/5.8.8/pod/perlapollo.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq4.pod
	/usr/lib/perl5/5.8.8/pod/perlfaq2.pod
	/usr/lib/perl5/5.8.8/pod/perlko.pod
	/usr/lib/perl5/5.8.8/pod/perlvos.pod
	/usr/lib/perl5/5.8.8/pod/perlebcdic.pod
	/usr/lib/perl5/5.8.8/pod/perlfilter.pod
	/usr/lib/perl5/5.8.8/pod/perlintern.pod
	/usr/lib/perl5/5.8.8/pod/perlthrtut.pod
	/usr/lib/perl5/5.8.8/pod/perldoc.pod
	/usr/lib/perl5/5.8.8/pod/perluts.pod
	/usr/lib/perl5/5.8.8/pod/perldiag.pod
	/usr/lib/perl5/5.8.8/complete.pl
	/usr/lib/perl5/5.8.8/CPAN/Nox.pm
	/usr/lib/perl5/5.8.8/CPAN/PAUSE2003.pub
	/usr/lib/perl5/5.8.8/CPAN/FirstTime.pm
	/usr/lib/perl5/5.8.8/CPAN/SIGNATURE
	/usr/lib/perl5/5.8.8/dbm_filter_util.pl
	/usr/lib/perl5/5.8.8/Thread.pm
	/usr/lib/perl5/5.8.8/FindBin.pm
	/usr/lib/perl5/5.8.8/DBM_Filter/null.pm
	/usr/lib/perl5/5.8.8/DBM_Filter/int32.pm
	/usr/lib/perl5/5.8.8/DBM_Filter/utf8.pm
	/usr/lib/perl5/5.8.8/DBM_Filter/encode.pm
	/usr/lib/perl5/5.8.8/DBM_Filter/compress.pm
	/usr/lib/perl5/5.8.8/Attribute/Handlers.pm
	/usr/lib/perl5/5.8.8/Devel/SelfStubber.pm
	/usr/lib/perl5/5.8.8/CPAN.pm
	/usr/lib/perl5/5.8.8/Dumpvalue.pm
	/usr/lib/perl5/5.8.8/newgetopt.pl
	/usr/lib/perl5/5.8.8/find.pl
	/usr/lib/perl5/5.8.8/syslog.pl
	/usr/lib/perl5/5.8.8/Net/POP3.pm
	/usr/lib/perl5/5.8.8/Net/SMTP.pm
	/usr/lib/perl5/5.8.8/Net/servent.pm
	/usr/lib/perl5/5.8.8/Net/netent.pm
	/usr/lib/perl5/5.8.8/Net/Hostname.eg
	/usr/lib/perl5/5.8.8/Net/hostent.pm
	/usr/lib/perl5/5.8.8/Net/libnetFAQ.pod
	/usr/lib/perl5/5.8.8/Net/FTP/L.pm
	/usr/lib/perl5/5.8.8/Net/FTP/dataconn.pm
	/usr/lib/perl5/5.8.8/Net/FTP/E.pm
	/usr/lib/perl5/5.8.8/Net/FTP/A.pm
	/usr/lib/perl5/5.8.8/Net/FTP/I.pm
	/usr/lib/perl5/5.8.8/Net/protoent.pm
	/usr/lib/perl5/5.8.8/Net/Time.pm
	/usr/lib/perl5/5.8.8/Net/Cmd.pm
	/usr/lib/perl5/5.8.8/Net/Config.eg
	/usr/lib/perl5/5.8.8/Net/Ping.pm
	/usr/lib/perl5/5.8.8/Net/NNTP.pm
	/usr/lib/perl5/5.8.8/Net/Netrc.pm
	/usr/lib/perl5/5.8.8/Net/Domain.pm
	/usr/lib/perl5/5.8.8/Net/FTP.pm
	/usr/lib/perl5/5.8.8/Net/Config.pm
	/usr/lib/perl5/5.8.8/Test/Harness.pm
	/usr/lib/perl5/5.8.8/Test/Builder.pm
	/usr/lib/perl5/5.8.8/Test/Harness/Assert.pm
	/usr/lib/perl5/5.8.8/Test/Harness/TAP.pod
	/usr/lib/perl5/5.8.8/Test/Harness/Iterator.pm
	/usr/lib/perl5/5.8.8/Test/Harness/Point.pm
	/usr/lib/perl5/5.8.8/Test/Harness/Straps.pm
	/usr/lib/perl5/5.8.8/Test/Tutorial.pod
	/usr/lib/perl5/5.8.8/Test/Simple.pm
	/usr/lib/perl5/5.8.8/Test/Builder/Tester.pm
	/usr/lib/perl5/5.8.8/Test/Builder/Tester/Color.pm
	/usr/lib/perl5/5.8.8/Test/Builder/Module.pm
	/usr/lib/perl5/5.8.8/Test/More.pm
	/usr/lib/perl5/5.8.8/getopt.pl
	/usr/lib/perl5/5.8.8/ctime.pl
	/usr/lib/perl5/5.8.8/Locale/Constants.pm
	/usr/lib/perl5/5.8.8/Locale/Script.pod
	/usr/lib/perl5/5.8.8/Locale/Maketext.pm
	/usr/lib/perl5/5.8.8/Locale/Country.pm
	/usr/lib/perl5/5.8.8/Locale/Maketext/GutsLoader.pm
	/usr/lib/perl5/5.8.8/Locale/Maketext/TPJ13.pod
	/usr/lib/perl5/5.8.8/Locale/Maketext/Guts.pm
	/usr/lib/perl5/5.8.8/Locale/Language.pod
	/usr/lib/perl5/5.8.8/Locale/Currency.pod
	/usr/lib/perl5/5.8.8/Locale/Currency.pm
	/usr/lib/perl5/5.8.8/Locale/Language.pm
	/usr/lib/perl5/5.8.8/Locale/Country.pod
	/usr/lib/perl5/5.8.8/Locale/Constants.pod
	/usr/lib/perl5/5.8.8/Locale/Maketext.pod
	/usr/lib/perl5/5.8.8/Locale/Script.pm
	/usr/lib/perl5/5.8.8/Search/Dict.pm
	/usr/lib/perl5/5.8.8/Switch.pm
	/usr/lib/perl5/5.8.8/Digest/base.pm
	/usr/lib/perl5/5.8.8/Digest/file.pm
	/usr/lib/perl5/5.8.8/FileCache.pm
	/usr/lib/perl5/5.8.8/auto/POSIX/SigAction/handler.al
	/usr/lib/perl5/5.8.8/auto/POSIX/SigAction/safe.al
	/usr/lib/perl5/5.8.8/auto/POSIX/SigAction/mask.al
	/usr/lib/perl5/5.8.8/auto/POSIX/SigAction/flags.al
	/usr/lib/perl5/5.8.8/bigfloat.pl
	/usr/lib/perl5/5.8.8/getopts.pl
	/usr/lib/perl5/5.8.8/bigrat.pl
	/usr/lib/perl5/5.8.8/Time/tm.pm
	/usr/lib/perl5/5.8.8/Time/gmtime.pm
	/usr/lib/perl5/5.8.8/Time/localtime.pm
	/usr/lib/perl5/5.8.8/Text/Balanced.pm
	/usr/lib/perl5/5.8.8/Text/Abbrev.pm
	/usr/lib/perl5/5.8.8/Text/Soundex.pm
	/usr/lib/perl5/5.8.8/abbrev.pl
	/usr/lib/perl5/5.8.8/Fatal.pm
	/usr/lib/perl5/5.8.8/hostname.pl
	/usr/lib/perl5/5.8.8/termcap.pl
	/usr/share/man/man1/perl570delta.1.gz
	/usr/share/man/man1/pl2pm.1.gz
	/usr/share/man/man1/perlpod.1.gz
	/usr/share/man/man1/perlform.1.gz
	/usr/share/man/man1/perlmod.1.gz
	/usr/share/man/man1/perlmpeix.1.gz
	/usr/share/man/man1/perlfaq4.1.gz
	/usr/share/man/man1/perlirix.1.gz
	/usr/share/man/man1/perlos390.1.gz
	/usr/share/man/man1/perlreref.1.gz
	/usr/share/man/man1/perlre.1.gz
	/usr/share/man/man1/h2xs.1.gz
	/usr/share/man/man1/perl5005delta.1.gz
	/usr/share/man/man1/perldbmfilter.1.gz
	/usr/share/man/man1/xsubpp.1.gz
	/usr/share/man/man1/perlhist.1.gz
	/usr/share/man/man1/perlfilter.1.gz
	/usr/share/man/man1/perldebug.1.gz
	/usr/share/man/man1/perlport.1.gz
	/usr/share/man/man1/perlbot.1.gz
	/usr/share/man/man1/perltooc.1.gz
	/usr/share/man/man1/perllexwarn.1.gz
	/usr/share/man/man1/perlboot.1.gz
	/usr/share/man/man1/perlcc.1.gz
	/usr/share/man/man1/enc2xs.1.gz
	/usr/share/man/man1/perlglossary.1.gz
	/usr/share/man/man1/perlbs2000.1.gz
	/usr/share/man/man1/pod2text.1.gz
	/usr/share/man/man1/perl571delta.1.gz
	/usr/share/man/man1/perltw.1.gz
	/usr/share/man/man1/perlapi.1.gz
	/usr/share/man/man1/perldebguts.1.gz
	/usr/share/man/man1/perlhpux.1.gz
	/usr/share/man/man1/perlgpl.1.gz
	/usr/share/man/man1/perlpacktut.1.gz
	/usr/share/man/man1/perl572delta.1.gz
	/usr/share/man/man1/perltrap.1.gz
	/usr/share/man/man1/perlobj.1.gz
	/usr/share/man/man1/perlretut.1.gz
	/usr/share/man/man1/perlsyn.1.gz
	/usr/share/man/man1/perliol.1.gz
	/usr/share/man/man1/perlmachten.1.gz
	/usr/share/man/man1/find2perl.1.gz
	/usr/share/man/man1/perlthrtut.1.gz
	/usr/share/man/man1/perluts.1.gz
	/usr/share/man/man1/perlclib.1.gz
	/usr/share/man/man1/perlbeos.1.gz
	/usr/share/man/man1/perlsolaris.1.gz
	/usr/share/man/man1/perl5004delta.1.gz
	/usr/share/man/man1/perldgux.1.gz
	/usr/share/man/man1/perlintern.1.gz
	/usr/share/man/man1/perlplan9.1.gz
	/usr/share/man/man1/psed.1.gz
	/usr/share/man/man1/a2p.1.gz
	/usr/share/man/man1/perlvos.1.gz
	/usr/share/man/man1/h2ph.1.gz
	/usr/share/man/man1/perl588delta.1.gz
	/usr/share/man/man1/perlfaq7.1.gz
	/usr/share/man/man1/perldos.1.gz
	/usr/share/man/man1/perlfaq.1.gz
	/usr/share/man/man1/perlbug.1.gz
	/usr/share/man/man1/perlbook.1.gz
	/usr/share/man/man1/perl561delta.1.gz
	/usr/share/man/man1/perltoot.1.gz
	/usr/share/man/man1/perlhurd.1.gz
	/usr/share/man/man1/perlxs.1.gz
	/usr/share/man/man1/perlmacosx.1.gz
	/usr/share/man/man1/perltru64.1.gz
	/usr/share/man/man1/perlfaq8.1.gz
	/usr/share/man/man1/perlguts.1.gz
	/usr/share/man/man1/perlmodlib.1.gz
	/usr/share/man/man1/perlfunc.1.gz
	/usr/share/man/man1/perlrequick.1.gz
	/usr/share/man/man1/perlapollo.1.gz
	/usr/share/man/man1/perl587delta.1.gz
	/usr/share/man/man1/perldoc.1.gz
	/usr/share/man/man1/perlos2.1.gz
	/usr/share/man/man1/perlmacos.1.gz
	/usr/share/man/man1/perlpodspec.1.gz
	/usr/share/man/man1/perlcn.1.gz
	/usr/share/man/man1/perlebcdic.1.gz
	/usr/share/man/man1/perluniintro.1.gz
	/usr/share/man/man1/cpan.1.gz
	/usr/share/man/man1/instmodsh.1.gz
	/usr/share/man/man1/perllinux.1.gz
	/usr/share/man/man1/perl583delta.1.gz
	/usr/share/man/man1/perlreftut.1.gz
	/usr/share/man/man1/perlmint.1.gz
	/usr/share/man/man1/perljp.1.gz
	/usr/share/man/man1/perlref.1.gz
	/usr/share/man/man1/perlintro.1.gz
	/usr/share/man/man1/perlepoc.1.gz
	/usr/share/man/man1/perl.1.gz
	/usr/share/man/man1/perldsc.1.gz
	/usr/share/man/man1/perlxstut.1.gz
	/usr/share/man/man1/perl581delta.1.gz
	/usr/share/man/man1/perlko.1.gz
	/usr/share/man/man1/dprofpp.1.gz
	/usr/share/man/man1/pod2man.1.gz
	/usr/share/man/man1/perlop.1.gz
	/usr/share/man/man1/perlhack.1.gz
	/usr/share/man/man1/pstruct.1.gz
	/usr/share/man/man1/perlothrtut.1.gz
	/usr/share/man/man1/perlfaq6.1.gz
	/usr/share/man/man1/perlnewmod.1.gz
	/usr/share/man/man1/perlos400.1.gz
	/usr/share/man/man1/perldebtut.1.gz
	/usr/share/man/man1/perltoc.1.gz
	/usr/share/man/man1/perlsec.1.gz
	/usr/share/man/man1/perlnetware.1.gz
	/usr/share/man/man1/perl584delta.1.gz
	/usr/share/man/man1/perlwin32.1.gz
	/usr/share/man/man1/perl585delta.1.gz
	/usr/share/man/man1/perltodo.1.gz
	/usr/share/man/man1/perlembed.1.gz
	/usr/share/man/man1/perlipc.1.gz
	/usr/share/man/man1/pod2html.1.gz
	/usr/share/man/man1/perlqnx.1.gz
	/usr/share/man/man1/perlopentut.1.gz
	/usr/share/man/man1/perlunicode.1.gz
	/usr/share/man/man1/perldelta.1.gz
	/usr/share/man/man1/perllocale.1.gz
	/usr/share/man/man1/perlmodinstall.1.gz
	/usr/share/man/man1/perltie.1.gz
	/usr/share/man/man1/perlvar.1.gz
	/usr/share/man/man1/perl56delta.1.gz
	/usr/share/man/man1/perlcompile.1.gz
	/usr/share/man/man1/splain.1.gz
	/usr/share/man/man1/perlmodstyle.1.gz
	/usr/share/man/man1/perlfaq2.1.gz
	/usr/share/man/man1/perldata.1.gz
	/usr/share/man/man1/perlopenbsd.1.gz
	/usr/share/man/man1/perlfork.1.gz
	/usr/share/man/man1/perl586delta.1.gz
	/usr/share/man/man1/pod2latex.1.gz
	/usr/share/man/man1/perlamiga.1.gz
	/usr/share/man/man1/perlartistic.1.gz
	/usr/share/man/man1/perlcall.1.gz
	/usr/share/man/man1/perlrun.1.gz
	/usr/share/man/man1/perlvms.1.gz
	/usr/share/man/man1/perlvmesa.1.gz
	/usr/share/man/man1/perlstyle.1.gz
	/usr/share/man/man1/perlapio.1.gz
	/usr/share/man/man1/perlce.1.gz
	/usr/share/man/man1/s2p.1.gz
	/usr/share/man/man1/perlaix.1.gz
	/usr/share/man/man1/perl58delta.1.gz
	/usr/share/man/man1/c2ph.1.gz
	/usr/share/man/man1/perldiag.1.gz
	/usr/share/man/man1/perl582delta.1.gz
	/usr/share/man/man1/piconv.1.gz
	/usr/share/man/man1/perlcygwin.1.gz
	/usr/share/man/man1/perllol.1.gz
	/usr/share/man/man1/perlfaq3.1.gz
	/usr/share/man/man1/perlsub.1.gz
	/usr/share/man/man1/libnetcfg.1.gz
	/usr/share/man/man1/perlnumber.1.gz
	/usr/share/man/man1/perl573delta.1.gz
	/usr/share/man/man1/perlfreebsd.1.gz
	/usr/share/man/man1/perlutil.1.gz
	/usr/share/man/man1/perlcheat.1.gz
	/usr/share/man/man1/perlfaq9.1.gz
	/usr/share/man/man1/perlivp.1.gz
	/usr/share/man/man1/perlfaq5.1.gz
	/usr/share/man/man1/perlfaq1.1.gz
	/usr/bin/{code2color,devdump}
	/usr/bin/{html2png,afmtodit,grolj4,oldfind}
	/usr/lib/groff
	/usr/lib/xorg/modules/multimedia
	/usr/lib/gtkmm*
	/usr/sbin/{ntpd,swat}
	/usr/share/fonts/75dpi/{a*,b*,c*,d*,e*,f*,g*,i*,j*,k*,li*,m*,n*,o*,p*,q*,r*,s*,t*,u*,v*,w*,x*,y*,z*}
	/usr/share/fonts/75dpi/helv*ISO8859-1.pcf.gz
	/usr/share/zoneinfo
	/usr/share/locale/{a*,b*,c*,d*,e*,f*,g*,h*,i*,j*,k*,lb,m*,n*,o*,p*,q*,r*,s*,t*,u*,v*,w*,x*,y*,z*}
	/usr/lib/locale/{a*,b*,c*,g*,h*,i*,j*,k*,l*,m*,n*,o*,p*,q*,r*,s*,t*,u*,v*,w*,x*,y*,z*}
	/usr/lib/locale/{da*,de_AT*,de_BE*,de_CH*,de_LU*,de_DE@euro,dz*}
	/usr/lib/locale/{en_AU*,en_BW*,en_CA*,en_DK*,en_HK*,en_IE*,en_IN*,en_NG*,en_NZ*,en_PH*,en_SG*,en_ZA*,en_ZW*}
	/usr/lib/locale/{es_*,et_*,eu_*,el_*}
	/usr/lib/locale/{fa*,fi*,fo*,fr_BE*,fr_CA*,fr_CH*,fr_LU*,fy*,fur_IT,fr_FR@euro}
	/usr/share/fonts/misc/6x10-ISO8859-{2,3,4,5,6,7,8,9,10,11,12,13,14}.pcf.gz
	/usr/share/fonts/cyrillic
	/usr/share/fonts/encodings/large
	/usr/share/fonts/misc/{*ja*,*ko*,k14*}
	/usr/share/i18n/charmaps/{GB18030.gz,EUC-TW.gz,CP949.gz,JOHAB.gz,GBK.gz,BIG5*,EUC*}
	/usr/share/i18n/charmaps/{SHIFT*,ISO_10646.gz,GB2312.gz,WINDOWS-31J.gz}
	/usr/share/ati/*
	/opt/bin/amdcccle
	/opt/bin/fglrxinfo
	/usr/lib/opengl/nvidia/*
	/usr/lib/opengl/nvidia/*
	/usr/lib/syslinux/com32
	/usr/lib/opengl/xorg-x11/include
	/usr/share/man/{bg,cs,da,de,el,es,fi,hr,ja,ko,nl,pt,ro,sl}
	/usr/bin/dar_static
	/usr/bin/{Xati,Xephyr,Xfake,Xi810,Xmga,Xvia}
	/usr/sbin/th_htpasswd
	/usr/include/{*mm*,poppler,openssl,nouveau,libxml2,geany,drm,irssi,dar,qemacs,selinux,gmpxx.h,reiser4}
	/usr/share/icons/Rodent
	/usr/lib/python*/test
	/usr/share/dict/
	/usr/share/i18n/locales/{a*,b*,c*,g*,h*,j*,k*,l*,m*,n*,o*,p*,q*,r*,s*,u*,v*,w*,x*,y*,z*}
	/usr/share/i18n/locales/{da*,dz*,de_AT*,de-CH*,de_BE*,es_*,et_*,eu_*,el_*,fa*,fi*,fo*,fr_BE*,fr_CH*,fr_LU*,fy*,fu*}
	/usr/share/i18n/locales/{en_AU,en_BW,en_CA,en_DK,en_HK,en_IE*,en_IN,en_NG,en_NZ,en_PH,en_SG,en_ZA,en_ZW}
	/usr/share/i18n/locales/{id_*,is_*,ik_*,ig_*,it_*,iu_*,iw_*}
	/usr/share/i18n/locales/{ta_*,te_*,tg_*,th_*,ti_*,tig*,tk_*,tl_*,tn_*,tr_*,ts_*,tt_*}
	/usr/share/i18n/locales/*
	/usr/share/X11/locale/{fi*,pt_BR*,el_GR*,zh*,ko*,ja*}
	/usr/share/groff/*/font/devlj4
	/usr/share/zsh/*/functions/Completion/{AIX,Debian,Cygwin,Darwin,Mandriva,Redhat}
	/usr/share/swig/*/{csharp,java,gcj,ruby,guile,modula3,php4}
	/usr/share/vim/vim7*/{doc,indent,keymap,spell,tutor,print}
	/usr/share/vim/vim7*/syntax/{php.vim,baan.vim,pfmain.vim,autoit.vim,xmodmap.vim}
	/usr/share/vim/vim7*/syntax/{postscr.vim,doxygen.vim,lisp.vim,foxpro.vim,sqlanywhere.vim}
	/usr/share/vim/vim7*/syntax/{maple.vim,ora.vim,ishd.vim,stata.vim,jam.vim,skill.vim}
	/usr/share/vim/vim7*/syntax/{rpl.vim,fortran.vim,aml.vim,fvwm.vim,lpc.vim,ruby.vim}
	/usr/share/vim/vim7*/syntax/{cdrtoc.vim,groovy.vim,vb.vim,progress.vim,vera.vim}
	/usr/share/vim/vim7*/syntax/{inform.vim,sudoers.vim,maxima.vim,idl.vim,sicad.vim,scheme.vim}
	/usr/share/vim/vim7*/syntax/{splint.vim,mupad.vim,nqc.vim,openroad.vim,hamster.vim}
	/usr/share/vim/vim7*/syntax/{sqr.vim,spup.vim,idlang.vim,ncf.vim,mush.vim,ocaml.vim}
	/usr/share/vim/vim7*/syntax/{slrnrc.vim,ada.vim,cmusrc.vim,logtalk.vim,sisu.vim}
	/usr/share/vim/vim7*/syntax/{lscript.vim,smcl.vim,mma.vim,lua.vim,virata.vim,slpconf.vim}
	/usr/share/vim/vim7*/syntax/{framescript.vim,xmath.vim,freebasic.vim,cobol.vim}
	/usr/share/vim/vim7*/syntax/{sml.vim,btm.vim,aspvbs.vim,moo.vim,jal.vim,pov.vim,nastran.vim}
	/usr/share/vim/vim7*/syntax/{forth.vim,csc.vim,fasm.vim,tsalt.vim,quake.vim,chill.vim}
	/usr/share/vim/vim7*/syntax/{mf.vim,rexx.vim,fgl.vim,specman.vim,radiance.vim,rst.vim}
	/usr/share/vim/vim7*/syntax/{tf.vim,tads.vim,ibasic.vim,uc.vim,omnimark.vim,a65.vim}
	/usr/share/vim/vim7*/syntax/{pike.vim,jess.vim,litestep.vim,lifelines.vim,abap.vim}
	/usr/share/vim/vim7*/syntax/{vhdl.vim,dcl.vim,kix.vim,sqlinformix.vim,rhelp.vim,wml.vim}
	/usr/share/vim/vim7*/syntax/{verilogams.vim,hercules.vim,cs.vim,b.vim,fdcc.vim}
	/usr/share/vim/vim7*/syntax/{smil.vim,jproperties.vim,clipper.vim,stp.vim,mp.vim}
	/usr/share/vim/vim7*/syntax/{wsml.vim,plm.vim,aap.vim,conaryrecipe.vim,racc.vim,pilrc.vim}
	/usr/share/vim/vim7*/syntax/{tsscl.vim,flexwiki.vim,trasys.vim,eviews.vim,abel.vim}
	/usr/share/vim/vim7*/syntax/{iss.vim,slpreg.vim,verilog.vim,pinfo.vim,acedb.vim,lite.vim}
	/usr/share/vim/vim7*/syntax/{mmix.vim,diva.vim,aflex.vim,lhaskell.vim,psf.vim,spyce.vim}
	/usr/share/vim/vim7*/syntax/{pccts.vim,lout.vim,occam.vim,ptcap.vim,sl.vim,lace.vim}
	/usr/share/vim/vim7*/syntax/{opl.vim,mplayerconf.vim,lprolog.vim,gkrellmrc.vim,snobol4.vim}
	/usr/share/vim/vim7*/syntax/{ampl.vim,prolog.vim,loginaccess.vim,cl.vim,cupl.vim}
	/usr/share/vim/vim7*/syntax/{gretl.vim,sinda.vim,papp.vim,django.vim,logindefs.vim}
	/usr/share/vim/vim7*/syntax/{expect.vim,latte.vim,tpp.vim,mgl.vim,modsim3.vim}
	/usr/share/vim/vim7*/syntax/{focexec.vim,bdf.vim,sather.vim,objc.vim,dylan.vim,msidl.vim}
	/usr/share/vim/vim7*/syntax/{mel.vim,pic.vim,hitest.vim,simula.vim,bib.vim,purifylog.vim}
	/usr/share/vim/vim7*/syntax/{gdmo.vim,modula2.vim,r.vim,privoxy.vim,slrnsc.vim,scilab.vim}
	/usr/share/vim/vim7*/syntax/{povini.vim,desc.vim,matlab.vim,webmacro.vim,mason.vim}
	/usr/share/vim/vim7*/syntax/{hb.vim,bst.vim,form.vim,amiga.vim,tak.vim,cdl.vim,dot.vim}
	/usr/share/vim/vim7*/syntax/{yaml.vim,sm.vim,cweb.vim,z8a.vim,elmfilt.vim,pod.vim}
	/usr/share/vim/vim7*/syntax/{slice.vim,ppwiz.vim,mib.vim,tssgm.vim,ahdl.vim,eruby.vim}
	/usr/share/vim/vim7*/syntax/{netrw.vim,esterel.vim,clean.vim,smarty.vim,dracula.vim}
	/usr/share/vim/vim7*/syntax/{st.vim,cynlib.vim,atlas.vim,uil.vim,kwt.vim,ayacc.vim,asn.vim}
	/usr/share/vim/vim7*/syntax/{prescribe.vim,gp.vim,lotos.vim,elf.vim}
	/usr/share/vim/vim7*/syntax/{pf.vim,snnsnet.vim,gedcom.vim,javacc.vim,spice.vim,esqlc.vim}
	/usr/share/vim/vim7*/syntax/{chordpro.vim,asmh8300.vim,texmf.vim,sd.vim,takout.vim}
	/usr/share/vim/vim7*/syntax/{rib.vim,modula3.vim,sindaout.vim,mgp.vim,cuplsim.vim,kscript.vim}
	/usr/share/vim/vim7*/syntax/{ist.vim,snnspat.vim,ave.vim,rnc.vim,abc.vim,remind.vim}
	/usr/share/vim/vim7*/syntax/{dcd.vim,tssop.vim,gsp.vim,snnsres.vim,cheetah.vim,xsd.vim}
	/usr/share/vim/vim7*/syntax/{grads.vim,pyrex.vim,tli.vim,rnoweb.vim,takcmp.vim,cynpp.vim}
	/usr/share/vim/vim7*/syntax/{sindacmp.vim,bzr.vim,sieve.vim,jgraph.vim,xs.vim,ecd.vim}
	/usr/share/vim/vim7*/syntax/{tilde.vim,trustees.vim,dylanintr.vim,abaqus.vim,README.txt}
	/usr/share/vim/vim7*/autoload/{README.txt,ada.vim,adacomplete.vim,decada.vim,gnat.vim}
	/usr/share/vim/vim7*/autoload/{spellfile.vim,phpcomplete.vim,netrw.vim,javascriptcomplete.vim}
	/usr/share/vim/vim7*/lang/menu_{ja*,ru*,vi*,zh*,sr*,sl*,ch*,it*,ca*,es*,pl*,po*,pt*}
	/usr/share/vim/vim7*/lang/menu_{cs*,cz*,sr*,hu*,no*,sv*,nl*,ko*,af*,sk*}
	/usr/share/vim/vim7*/macro/{hanoi*,life*,maze*,urm*}
	/usr/share/vim/vim7*/ftplugin/{ocaml.vim,cobol.vim,ada.vim,Append*,vhdl.vim,eruby.vim}
	/usr/share/vim/vim7*/ftplugin/{abaqus.vim,vb.vim,hamster.vim,aspvbs.vim,flexwiki.vim}
	/usr/share/vim/vim7*/ftplugin/{verilog.vim,lprolog.vim,ishd.vim,xsd.vim,scheme.vim,occam.vim}
	/usr/share/vim/vim7*/ftplugin/{mupad.vim,lua.vim,lisp.vim,aap.vim,pyrex.vim,matlab.vim}
	/usr/share/xfce4/backdrops/{flower.png,xfce-*png}
	/usr/share/xfce4/doc
	/usr/share/alsa
	/usr/share/icons/hicolor/icon-theme.cache
	/usr/share/icons/gnome/scalable
	/usr/share/icons/gnome/256x256
	/usr/include/{alsa,nspr,OpenIPMI,nss,xorg,hunspell,xulrunner*,netlink,xfce4,exo*}
	/usr/lib/portage/pym/cache/{*.pyo,*.pyc}
	/usr/lib/portage/pym/elog_modules/{*.pyo,*.pyc}
	/usr/lib/portage/pym/{*.pyo,*.pyc}
	/usr/lib/python*/pym/{*.pyo,*.pyc}
	/usr/lib/gentoolkit/pym/gentoolkit/{*.pyo,*.pyc}
	/usr/share/dstat/{*.pyo,*.pyc}
	/usr/bin/{Xchips,Xepson,Xmach64,Xnest,Xpm2,Xr128,Xsmi,Xvfb}
	/usr/share/gcc-data/i486-pc-linux-gnu/*/{info,locale}
	/usr/share/binutils-data/i486-pc-linux-gnu/*/{info,locale}
	/usr/lib/mozilla-firefox/xpidl
	/usr/bin/fgl_glxgears
	/usr/include/{X11,sigc++*,python*}
	/usr/lib/cracklib_dict.*
	/usr/share/dmraid
	/usr/bin/{net,rpcclient,smbget,smbcacls,smbcquotas,smbclient,smbtree,smbmount,smbumount,smbspool}
	/usr/lib/xorg/modules/extensions/libglx.so
	/usr/lib/opengl/xorg-x11/extensions/libglx.so
	/usr/lib/dri

