subarch: i686
version_stamp: baseos
target: stage3
rel_type: default
profile: default/linux/x86/17.0
snapshot: 20180914
source_subpath: default/stage2-i686-baseos
portage_confdir: /worksrc/sysresccd-src/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src/portage-overlay
