subarch: i386
version_stamp: 1.5
target: livecd-stage1
rel_type: default
profile: default/linux/x86/10.0
snapshot: 20100707
source_subpath: default/stage4-i386-20100619-01
portage_confdir: /worksrc/sysresccd-src-1.5/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src-1.5/portage-overlay

livecd/use: -svg -opengl -glx -berkdb -gdbm -minimal dri X bindist fbcon ipv6 livecd ncurses pam readline ssl unicode zlib nptl nptlonly multilib jfs ntfs reiserfs xfs fat reiser4 samba gtk gtk2 png jpeg xorg usb pdf acl nologin atm bash-completion slang kdrive vram loop-aes crypt device-mapper 7zip xattr bzip2 server lzo xpm bash-completion -fam -doc -hardened -spoof-source -static -tcpd -mailwrapper -milter -nls -selinux -ermt -pic -dar32 -dar64 -openct -pcsc-lite -smartcard -caps -qt3 -qt4 -aqua -cscope -gnome -gpm -motif -netbeans -nextaw -perl -python -ruby -xterm -emacs -justify -spell -vim-pager -vim-with-x -sqlite -afs -bashlogger -plugins -vanilla -examples -maildir -pcre -accessibility -ithreads -perlsuid -php -pike -tcl -tk -nocxx -no-net2 -kerberos -sse2 -aio -cups -ldap -quotas -swat -syslog -winbind -socks5 -guile -X509 dbus -gnutls -gsm -cracklib -nousuid -skey -old-linux -pxeserial -multislot -multitarget -test -clvm -cman -gulm -gd -glibc-compat20 -glibc-omitfp -bidi -xinerama -qt3support -alsa -xcb

livecd/packages:
	=sys-boot/grub-0.97-r9
	app-accessibility/speakup-utils
	app-admin/ide-smart
	app-admin/hddtemp
	app-admin/hwreport
	sys-boot/mbr
	app-admin/passook
	app-admin/procinfo-ng
	app-admin/pwgen
	app-admin/sudo
	app-admin/syslog-ng
	app-admin/sysstat
	app-admin/testdisk
	app-antivirus/clamav
	app-arch/afio
	app-arch/arj
	app-arch/bzip2
	app-arch/cabextract
	app-arch/cfv
	app-arch/cpio
	app-arch/dump
	app-arch/gzip
	app-arch/lzip
	app-arch/lzop
	app-arch/xz-utils
	app-arch/mscompress
	app-arch/mt-st
	app-arch/ncompress
	app-arch/p7zip
	app-arch/pbzip2
	app-arch/par2cmdline
	app-arch/pigz
	app-arch/rar
	app-arch/rpm2targz
	app-arch/rzip
	app-arch/sharutils
	app-arch/tar
	app-arch/unace
	app-arch/unrar
	app-arch/unzip
	app-arch/zip
	app-arch/xarchiver
	app-misc/beep
	app-misc/emelfm2
	app-vim/gentoo-syntax
	app-backup/dar
	app-backup/duplicity
	app-backup/rdiff-backup
	app-backup/rsnapshot
	app-backup/tob
	app-benchmarks/bonnie++
	app-benchmarks/cpuburn
	app-benchmarks/iozone
	app-benchmarks/stress
	app-portage/eix
	app-cdr/cdw
	app-cdr/dvd+rw-tools
	app-cdr/xfburn
	app-crypt/chntpw
	app-crypt/md5deep
	app-editors/gvim
	app-editors/hexedit
	app-editors/hexcurse
	app-editors/joe
	app-editors/nano
	app-editors/qemacs
	app-editors/vim
	app-editors/vim-core
	app-editors/zile
	app-forensics/afflib
	app-forensics/chkrootkit
	app-forensics/cmospwd
	app-forensics/foremost
	app-forensics/magicrescue
	app-forensics/sleuthkit
	app-misc/ckermit
	app-misc/colordiff
	app-misc/livecd-tools
	app-misc/mc
	app-misc/screen
	app-misc/symlinks
	app-misc/vlock
	app-misc/wipe
	app-portage/gentoolkit
	app-portage/mirrorselect
	app-shells/bash
	app-shells/ksh
	app-shells/tcsh
	app-shells/zsh
	app-text/dos2unix
	app-text/epdfview
	dev-lang/perl
	dev-libs/expat
	dev-libs/libconfig
	dev-libs/lzo
	dev-libs/openssl
	dev-libs/popt
	dev-libs/pkcs11-helper
	dev-python/pyparted
	dev-util/cmake
	dev-util/geany
	dev-util/intltool
	dev-util/pkgconfig
	dev-util/ltrace
	dev-util/strace
	gnome-extra/nm-applet
	lxde-base/lxrandr
	media-fonts/terminus-font
	net-analyzer/arping
	net-analyzer/dnstracer
	net-analyzer/httping
	net-analyzer/ifstat
	net-analyzer/iftop
	net-analyzer/iptraf
	net-analyzer/macchanger
	net-analyzer/netcat
	net-analyzer/ngrep
	net-analyzer/nmap
	net-analyzer/tcpdump
	net-analyzer/tcptraceroute
	net-analyzer/traceroute
	net-analyzer/vnstat
	net-dialup/gtkterm
	net-dialup/linux-atm
	net-dialup/mingetty
	net-dialup/minicom
	net-dialup/ppp
	net-dialup/pppconfig
	net-dialup/pptpclient
	net-dns/bind-tools
	net-firewall/iptables
	sys-fs/dd-rhelp
	sys-fs/mtd-utils
	net-fs/mount-cifs
	net-fs/nfs-utils
	net-fs/samba
	net-ftp/ftp
	net-ftp/lftp
	net-ftp/ncftp
	net-ftp/tftp-hpa
	net-irc/irssi
	net-misc/autossh
	net-misc/dhcp
	net-misc/bridge-utils
	net-misc/dhcpcd
	net-misc/ethercard-diag
	net-misc/ifenslave
	net-misc/iperf
	net-misc/iputils
	net-misc/netkit-rsh
	net-misc/networkmanager
	net-misc/ntp
	net-misc/openssh
	net-misc/openvpn
	net-misc/rdate
	net-misc/rdesktop
	net-misc/rsync
	net-misc/telnet-bsd
	net-misc/udpcast
	net-misc/vconfig
	net-misc/tigervnc
	net-misc/vpnc
	net-misc/wget
	net-misc/whois
	net-misc/wput
	net-nds/portmap
	net-wireless/iw
	net-wireless/wireless-tools
	net-wireless/wpa_supplicant
	sys-apps/acl
	sys-apps/attr
	sys-apps/cciss_vol_status
	sys-apps/coreutils
	sys-apps/dcfldd
	sys-apps/debianutils
	sys-apps/diffutils
	sys-apps/dmapi
	sys-apps/dmidecode
	sys-apps/dstat
	sys-apps/dumpdisklayout
	sys-apps/ed
	sys-apps/eject
	sys-apps/ethtool
	sys-apps/fbset
	sys-apps/file
	sys-apps/findutils
	sys-apps/flashrom
	sys-apps/fxload
	sys-apps/gawk
	sys-apps/gdisk
	sys-apps/groff
	sys-apps/hdparm
	sys-apps/hwsetup
	sys-apps/ipmitool
	sys-apps/kbd
	sys-apps/lshw
	sys-apps/man-pages
	sys-apps/memtester
	sys-apps/miscfiles
	sys-apps/net-tools
	sys-apps/netplug
	sys-apps/openrc
	sys-apps/parted
	sys-apps/pciutils
	sys-apps/pcmciautils
	sys-apps/pv
	sys-apps/ren
	sys-apps/rename
	sys-apps/rescan-scsi-bus
	sys-apps/sdparm
	sys-apps/sed
	sys-apps/setserial
	sys-apps/sg3_utils
	sys-apps/shadow
	sys-apps/slocate
	sys-apps/smartmontools
	sys-apps/tcp-wrappers
	sys-apps/usbutils
	sys-apps/util-linux
	sys-apps/which
	sys-apps/x86info
	sys-auth/pambase
	sys-block/gpart
	sys-block/gparted
	sys-block/lsiutil
	sys-block/mbuffer
	sys-block/mpt-status
	sys-block/ms-sys
	sys-block/mtx
	sys-block/nbd
	sys-block/partclone
	sys-block/tw_cli
	sys-block/megarc
	sys-block/megacli
	=sys-block/partimage-0.6.8
	sys-block/scsiadd
	sys-boot/lilo
	sys-boot/syslinux
	sys-devel/bc
	sys-devel/crossdev
	sys-devel/gettext
	sys-fs/btrfs-progs
	sys-fs/cryptsetup
	sys-fs/dd-rescue
	sys-fs/ddrescue
	sys-fs/dmraid
	sys-fs/diskdev_cmds
	sys-fs/dosfstools
	sys-fs/e2fsprogs
	sys-fs/ext3grep
	sys-fs/fsarchiver
	sys-fs/hfsplusutils
	sys-fs/hfsutils
	sys-fs/jfsutils
	sys-fs/lde
	sys-fs/lsscsi
	sys-fs/lvm2
	sys-fs/mdadm
	sys-fs/multipath-tools
	sys-fs/ntfs3g
	sys-fs/ntfsprogs
	sys-fs/ntfsreloc
	sys-fs/reiser4progs
	sys-fs/reiserfsprogs
	sys-fs/scrounge-ntfs
	sys-fs/squashfs-tools
	sys-fs/udev
	sys-fs/udftools
	sys-fs/xfsdump
	sys-fs/xfsprogs
	sys-kernel/gentoo-sources
	sys-libs/libstdc++-v3
	sys-libs/openipmi
	sys-libs/pam
	sys-libs/pwdb
	sys-libs/readline
	sys-libs/zlib
	sys-process/atop
	sys-process/cronbase
	sys-process/htop
	sys-process/iotop
	sys-process/lsof
	sys-process/procps
	sys-process/psmisc
	sys-process/vixie-cron
	x11-terms/terminal
	x11-apps/setxkbmap
	x11-apps/xcalc
	x11-apps/xgamma
	x11-apps/xkbcomp
	x11-apps/xdpyinfo
	x11-apps/xhost
	x11-apps/xmodmap
	x11-apps/xrandr
	x11-apps/xset
	x11-apps/xwd
	x11-base/xorg-server
	x11-drivers/xf86-input-evdev
	x11-drivers/xf86-input-keyboard
	x11-drivers/xf86-input-mouse
	x11-drivers/xf86-input-vmmouse
	x11-libs/wxGTK
	x11-proto/glproto
	x11-proto/xf86driproto
	x11-proto/inputproto
	x11-proto/xf86miscproto
	x11-proto/xineramaproto
	x11-proto/xextproto
	x11-misc/mkxf86config
	x11-misc/read-edid
	x11-misc/util-macros
	x11-misc/xkeyboard-config
	x11-wm/jwm
	x11-terms/mrxvt
	xfce-base/xfce4-meta
	x11-themes/gnome-icon-theme
	xfce-extra/xfce4-wavelan-plugin
	xfce-extra/xfce4-taskmanager
	xfce-extra/xfce4-datetime-plugin
	xfce-extra/xfce4-sensors-plugin
	sys-apps/iproute2
	www-client/elinks
	www-client/firefox-bin
	www-servers/thttpd

