subarch: amd64
version_stamp: baseos
target: stage3
rel_type: default
profile: default/linux/amd64/17.0
snapshot: 20180901
source_subpath: default/stage2-amd64-baseos
portage_confdir: /worksrc/sysresccd-src/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src/portage-overlay
