subarch: amd64
version_stamp: default
target: livecd-stage1
rel_type: default
profile: default/linux/x86/10.0
snapshot: 20120507
source_subpath: default/stage4-amd64-20120505-01
portage_confdir: /worksrc/sysresccd-src/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src/portage-overlay

livecd/use: -* X bindist fbcon ipv6 livecd ncurses pam readline ssl unicode zlib nptl nptlonly multilib jfs ntfs reiserfs xfs fat reiser4 gtk2 png jpeg -svg -opengl xorg usb pdf acl nologin -dri -glx minimal -atm -berkdb -gdbm slang -fortran -nls

livecd/packages:
	app-admin/hddtemp
	app-admin/hwreport
	app-admin/ide-smart
	app-admin/mcelog
	app-admin/passook
	app-admin/procinfo-ng
	app-admin/pwgen
	app-admin/sudo
	app-admin/syslog-ng
	app-admin/sysstat
	app-admin/testdisk
	app-arch/afio
	app-arch/arj
	app-arch/bzip2
	app-arch/cabextract
	#app-arch/cfv
	app-arch/cpio
	#app-arch/dpkg
	app-arch/dump
	app-arch/gzip
	app-arch/lzip
	app-arch/lzop
	app-arch/mscompress
	app-arch/mt-st
	app-arch/ncompress
	app-arch/p7zip
	app-arch/par2cmdline
	app-arch/pbzip2
	app-arch/pigz
	app-arch/rar
	app-arch/rzip
	app-arch/sharutils
	app-arch/tar
	app-arch/unace
	app-arch/unrar
	app-arch/unshield
	app-arch/unzip
	app-arch/xz-utils
	app-arch/zip
	#app-backup/bacula
	app-backup/dar
	app-backup/duplicity
	app-backup/fsarchiver
	app-backup/rdiff-backup
	app-backup/rsnapshot
	#app-backup/tob
	#app-benchmarks/bonnie++
	#app-benchmarks/iozone
	#app-benchmarks/stress
	#app-benchmarks/systester
	app-cdr/dvd+rw-tools
	app-crypt/chntpw
	app-crypt/md5deep
	app-editors/hexcurse
	app-editors/hexedit
	app-editors/joe
	app-editors/nano
	app-editors/vim
	app-editors/vim-core
	app-editors/zile
	#app-forensics/afflib
	#app-forensics/chkrootkit
	#app-forensics/cmospwd
	#app-forensics/foremost
	#app-forensics/magicrescue
	#app-forensics/sleuthkit
	#app-misc/colordiff
	#app-misc/fdupes
	app-misc/livecd-tools
	app-misc/screen
	#app-misc/scrub
	#app-misc/secure-delete
	app-misc/symlinks
	#app-misc/tmux
	#app-misc/vlock
	#app-misc/wipe
	app-portage/eix
	app-portage/gentoolkit
	app-portage/mirrorselect
	app-shells/bash
	#app-shells/ksh
	app-shells/tcsh
	app-shells/zsh
	app-text/dos2unix
	app-text/tree
	#app-text/wgetpaste
	app-vim/gentoo-syntax
	dev-lang/perl
	#dev-lang/ruby
	dev-libs/lzo
	dev-libs/openssl
	#dev-libs/pkcs11-helper
	#dev-libs/popt
	dev-util/intltool
	dev-util/ltrace
	dev-util/pkgconfig
	dev-util/strace
	net-analyzer/arping
	net-analyzer/dnstracer
	net-analyzer/httping
	net-analyzer/ifstat
	net-analyzer/iftop
	net-analyzer/iptraf-ng
	net-analyzer/macchanger
	net-analyzer/netcat
	net-analyzer/ngrep
	net-analyzer/nmap
	net-analyzer/tcpdump
	net-analyzer/tcptraceroute
	net-analyzer/traceroute
	net-analyzer/vnstat
	#net-dialup/linux-atm
	#net-dialup/mingetty
	net-dialup/minicom
	net-dialup/ppp
	net-dialup/pppconfig
	#net-dialup/pptpclient
	#net-dialup/rp-pppoe
	net-dns/bind-tools
	net-firewall/ipsec-tools
	net-firewall/iptables
	net-fs/mount-cifs
	net-fs/nfs-utils
	#net-fs/samba
	net-ftp/ftp
	net-ftp/lftp
	#net-ftp/ncftp
	net-misc/autossh
	net-misc/bridge-utils
	net-misc/dhcp
	net-misc/dhcpcd
	#net-misc/ethercard-diag
	net-misc/ifenslave
	net-misc/iperf
	net-misc/iputils
	#net-misc/netkit-rsh
	net-misc/ntp
	#net-misc/openssh
	net-misc/openvpn
	net-misc/rdate
	net-misc/rsync
	net-misc/telnet-bsd
	net-misc/udpcast
	net-misc/vconfig
	net-misc/vpnc
	net-misc/wget
	net-misc/whois
	net-misc/wput
	#net-wireless/acx-firmware
	#net-wireless/atmel-firmware
	#net-wireless/b43-fwcutter
	#net-wireless/bcm43xx-fwcutter
	#net-wireless/ipw2100-firmware
	#net-wireless/ipw2200-firmware
	net-wireless/iw
	#net-wireless/linux-wlan-ng-firmware
	#net-wireless/madwifi-ng-tools
	#net-wireless/prism54-firmware
	#net-wireless/rtl8192su-firmware
	#net-wireless/wireless-tools
	#net-wireless/zd1201-firmware
	#net-wireless/zd1211-firmware
	sys-apps/acl
	sys-apps/attr
	sys-apps/cciss_vol_status
	sys-apps/coreutils
	#sys-apps/dcfldd
	sys-apps/diffutils
	sys-apps/dmapi
	sys-apps/dmidecode
	sys-apps/dstat
	sys-apps/dumpdisklayout
	sys-apps/ed
	sys-apps/ethtool
	#sys-apps/fbset
	sys-apps/file
	sys-apps/findutils
	#sys-apps/flashrom
	#sys-apps/fxload
	sys-apps/gawk
	sys-apps/gptfdisk
	sys-apps/hdparm
	sys-apps/hwsetup
	#sys-apps/ipmitool
	sys-apps/iproute2
	sys-apps/kbd
	sys-apps/lm_sensors
	sys-apps/man-pages
	sys-apps/memtester
	sys-apps/miscfiles
	sys-apps/mlocate
	sys-apps/netplug
	sys-apps/net-tools
	sys-apps/openrc
	sys-apps/pciutils
	sys-apps/pcmciautils
	sys-apps/pv
	sys-apps/rename
	sys-apps/rescan-scsi-bus
	sys-apps/sdparm
	sys-apps/sed
	sys-apps/setserial
	sys-apps/sg3_utils
	sys-apps/shadow
	sys-apps/smartmontools
	sys-apps/tcp-wrappers
	sys-apps/usb_modeswitch
	sys-apps/usbutils
	sys-apps/util-linux
	sys-apps/which
	sys-apps/x86info
	#sys-block/aic94xx-firmware
	sys-block/eject
	sys-block/gpart
	sys-block/lsiutil
	sys-block/mbuffer
	sys-block/megacli
	sys-block/megarc
	sys-block/mpt-status
	sys-block/ms-sys
	sys-block/mtx
	sys-block/nbd
	sys-block/partclone
	sys-block/parted
	sys-block/partimage
	sys-block/scsiadd
	sys-block/tw_cli
	sys-boot/efibootmgr
	sys-boot/syslinux
	sys-cluster/drbd
	sys-devel/autogen
	sys-devel/bc
	sys-devel/crossdev
	#sys-devel/gettext
	sys-fs/btrfs-progs
	sys-fs/cryptsetup
	sys-fs/ddrescue
	sys-fs/dd-rescue
	sys-fs/diskdev_cmds
	sys-fs/dmraid
	sys-fs/dosfstools
	sys-fs/e2fsprogs
	sys-fs/ext3grep
	sys-fs/extundelete
	sys-fs/hfsplusutils
	sys-fs/hfsutils
	sys-fs/jfsutils
	#sys-fs/lde
	sys-fs/lsscsi
	sys-fs/lufis
	sys-fs/lufs
	sys-fs/lvm2
	sys-fs/mac-fdisk
	sys-fs/mdadm
	sys-fs/mtd-utils
	sys-fs/multipath-tools
	sys-fs/ntfs3g
	sys-fs/ntfsreloc
	sys-fs/reiser4progs
	sys-fs/reiserfsprogs
	sys-fs/scrounge-ntfs
	sys-fs/squashfs-tools
	sys-fs/sshfs-fuse
	sys-fs/udftools
	sys-fs/xfsdump
	#sys-fs/xfsprogs
	#sys-kernel/gentoo-sources
	#sys-kernel/linux-firmware
	sys-libs/libstdc++-v3
	#sys-libs/openipmi
	sys-libs/pam
	sys-libs/pwdb
	sys-libs/readline
	sys-libs/zlib
	#sys-process/atop
	#sys-process/cronbase
	sys-process/htop
	sys-process/iotop
	sys-process/lsof
	#sys-process/nmon
	sys-process/procps
	sys-process/psmisc
	sys-process/vixie-cron

