subarch: amd64
target: stage2
version_stamp: baseos
rel_type: default
profile: default/linux/amd64/13.0
snapshot: 20150522
source_subpath: default/stage1-amd64-baseos
portage_confdir: /worksrc/sysresccd-src/portage-etc-x86
portage_overlay: /worksrc/sysresccd-src/portage-overlay
