0C 
 ____            _                 ____                            ____    _ 
/ ___| _   _ ___| |_ ___ _ __ ___ |  _ \ ___  ___  ___ _   _  ___ / ___|__| |
\___ \| | | / __| __/ _ \ '_ ` _ \| |_) / _ \/ __|/ __| | | |/ _ \ |   / _` |
 ___) | |_| \__ \ ||  __/ | | | | |  _ <  __/\__ \ (__| |_| |  __/ |__| (_| |
|____/ \__, |___/\__\___|_| |_| |_|_| \_\___||___/\___|\__,_|\___|\____\__,_|
       |___/                                                                 
07
0C*07 Linux kernel-3.x (with ext4, btrfs filesystems support)
0C*07 Both 32bits (IA32) and 64bits (AMD64/EM64T) are supported
0C*07 GParted graphical partitioning tool (partition magic clone)
0C*07 File systems tools (ext3, ext4, reiserfs, ntfs, btrfs, ...) and LVM2
0C*07 Disk tools (parted, sfdisk, partimage, fsarchiver, testdisk, photorec)
0C*07 Ntfs-3g (ntfs full read-write support) and ntpass (reset windows passwords)
0C*07 Network tools (samba, nfs, ssh, lftp, tcpdump, ...) and wireless drivers
0C*07 Network booting via PXE (press F6 for help)

0C*07 X.Org / Xfbdev graphical environments with XFCE and Firefox-5.0
0C*07 Hardware autodetection and Midnight Commander

02==>07 0EPress F5 for help if you have boot problems with SystemRescueCd 02<==07 

Welcome to 0CSystemRescueCd07 for 0Cx86 07(i486+amd64)07 - version 0CSRCDVER
0fF2,F3,F4,F5,F6,F707 for boot options and more help. 
0fEnter07 to boot.
