<ALL> 0C 
<ALL> ____            _                 ____                            ____    _ 
<ALL> / ___| _   _ ___| |_ ___ _ __ ___ |  _  ___  ___  ___ _   _  ___ / ___|__| |
<ALL> ___ | | | / __| __/ _  '_ ` _ | |_) / _ / __|/ __| | | |/ _  |   / _` |
<ALL> ___) | |_| __  ||  __/ | | | | |  _ <  __/__  (__| |_| |  __/ |__| (_| |
<ALL> |____/ __, |___/_____|_| |_| |_|_| ____||___/___|__,_|___|______,_|
<ALL> |___/                                                                 
<ALL> 07
<ALL> 0C*07 Linux kernel-3.x (with ext4, btrfs filesystems support)
<ALL> 0C*07 Both 32bits (IA32) and 64bits (AMD64/EM64T) are supported
<ALL> 0C*07 GParted graphical partitioning tool (partition magic clone)
<ALL> 0C*07 File systems tools (ext3, ext4, reiserfs, ntfs, btrfs, ...) and LVM2
<ALL> 0C*07 Disk tools (parted, sfdisk, partimage, fsarchiver, testdisk, photorec)
<ALL> 0C*07 Ntfs-3g (ntfs full read-write support) and ntpass (reset windows passwords)
<ALL> 0C*07 Network tools (samba, nfs, ssh, lftp, tcpdump, ...) and wireless drivers
<ALL> 0C*07 Network booting via PXE (press F6 for help)
<ALL> 
<ALL> 0C*07 X.Org graphical environments with XFCE
<ALL> 0C*07 Hardware autodetection and Midnight Commander
<ALL> 
<ALL> 02==>07 0EPress F5 for help if you have boot problems with SystemRescueCd 02<==07 
<ALL> 
<ALL> Welcome to 0CSystemRescueCd07 for 0Cx86 07(i486+amd64)07 - version 0C<SRCDVER>
<ALL> 0fF2,F3,F4,F5,F6,F707 for boot options and more help. 
<ALL> 0fEnter07 to boot.
