<ALL> 
<ALL> 070FF107 | 0CF207 | 0FF307 | 0FF407 | 0FF507 | 0FF607 | 0FF707        0CSystemRescueCd07          09[boot images]07
<ALL> 
<ALL> Type the image name choosen (followed by options if needed) then press 0CEnter07
<ALL> For instance type 0Frescuecd docache07 to boot the default image with that option
<ALL> 
<ALL> 0C*07 0EMain images to boot linux from the livecd07:
<ALL> 0Frescuecd07     Default: boot either rescue32 or rescue64 depending on CPU type
<ALL> 0Frescue3207     Standard 32bit kernel for x86, should work on any PC
<ALL> 0Frescue6407     Standard 64bit kernel (required to run/chroot to 64bit binaries)
<ALL> 
<ALL> 0C*07 0EFloppy disk boot images07:
<ALL> 0Fmemtest07      Run memtest+ (memory tester)
<ALL> 0Fntpasswd07     Edit/reset Windows passwords even on NTFS disks (supports Win7)
<ALL> 0Ffreedos07      Run FreeDos (run DOS programs from a free OS)
<ALL> 0Fhdt07          Hardware Detection tool
<ALL> 0Fdban07         Tool that wipes all data of a computer
<ALL> 0Fmhdd07         Low-level Hard-Disk disagnostic tool
<ALL> 0Fnetboot07      Etherboot network booting images
<ALL> 0Fgrubdisk07     Super Grub Floppy Disk (includes Grub2)
<ALL> 0Fdisk107        Boot from the first hard disk
<ALL> 0Fdisk207        Boot from the second hard disk
<ALL> 
