 
070FF107 | 0CF207 | 0FF307 | 0FF407 | 0FF507 | 0FF607 | 0FF707        0CSystemRescueCd07            09[boot images]07

Type the image name choosen (followed by options if necessary) then press 0CEnter07
For instance type 0Frescuecd docache07 to boot the default image with that option

0C*07 0EMain images to boot linux from the livecd07:
0Frescuecd07     Default: main 32bits kernel for x86, should work
0Frescue6407     Kernel for amd64 (if you have to chroot on a 64bits system)
0Faltker3207     Alternative 32 bits kernel (use it if problems with rescuecd)
0Faltker6407     Alternative 64 bits kernel (use it if problems with rescue64)

0C*07 0EFloppy disk boot images07:
0Fmemtest07      Run memtest+ (memory tester)
0Fntpasswd07     Edit/reset Windows passwords even on NTFS disks (supports Vista)
0Ffreedos07      Run FreeDos (run DOS programs from a free OS)
0Fgag07          Run GAG (Graphical Boot Manager)
0Franish07       Run Ranish Partition Manager
0Fhdt07          Hardware Detection tool 
0Fdban07         Tool that wipes all data of a computer
0Fmhdd07         Low-level Hard-Disk disagnostic tool
0Fnetboot07      Etherboot network booting images
0Fgrubdisk07     Super Grub Floppy Disk (includes Grub2)
0Fdisk107        Boot from the first hard disk
 
