#!/bin/bash

# --------------------------------- variables -----------------------------
curtime="$(date +%Y%m%d-%H:%M:%S)"
forcevesa='0'
argv="$@"

# ------------------------------ parse options -----------------------------
if [ -f /root/xserver.cfg ]
then
	options="$(cat /root/xserver.cfg)"
else
	options="$(cat /proc/cmdline)"
fi

for x in ${options}
do
	case "${x}" in
		forcevesa)
			forcevesa=1
			;;
		forcexorg)
			forcevesa=0
			;;
	esac
done

# ----------------------------------- main --------------------------------
if [ "${forcevesa}" = '1' ]
then
	cmd="exec /usr/bin/Xfbdev -dumb -mouse mouse,/dev/input/mice -keybd keyboard,xkbmodel=pc105"
	echo "${curtime}: ${cmd}" >> /var/log/debugx.log
	${cmd}
	exit 0
else
	cmd="exec /usr/bin/Xorg ${argv}"
	echo "${curtime}: ${cmd}" >> /var/log/debugx.log
	${cmd}
	exit 0
fi

