# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1250937314);
user_pref("app.update.lastUpdateTime.background-update-timer", 1250937314);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1250937314);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1250937314);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1250937330);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1250937315);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "http://www.sysresccd.org/\r");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.1.2");
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.5.2");
user_pref("extensions.lastAppVersion", "3.5.2");
user_pref("extensions.update.enabled", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1253529337);
